// 自動生成ファイル（直接編集しない）。元は art/art_icons.mjs。npm run build-art で作り直す。
// 12x12 の小さなアイコン（地図のマス・持ち物・ステータス）。

import type { Sprite } from './types';

export type IconName =
  | 'battle'
  | 'elite'
  | 'rest'
  | 'shop'
  | 'treasure'
  | 'event'
  | 'boss'
  | 'item'
  | 'book'
  | 'weapon'
  | 'armor'
  | 'acc'
  | 'gold'
  | 'pair'
  | 'job'
  | 'floor'
  | 'blessing'
  | 'skull'
  | 'heart';

export const ICONS: Record<IconName, Sprite> = {
  battle: {
    pal: { k: '#0d0b10', a: '#a8b0bc', A: '#6a7280', w: '#6a4a2a', o: '#c9a54a' },
    rows: [
      '.k........k.',
      'kak......kak',
      '.kak....kak.',
      '.kAak..kaAk.',
      '..kAakkaAk..',
      '...kAaaAk...',
      '....kAak....',
      '..kkaAAakk..',
      '.kowaAkAwok.',
      '.kowkk.kkwok',
      'kwwk....kwwk',
      '.kk......kk.',
    ],
  },
  elite: {
    pal: { k: '#0d0b10', b: '#d8d0b8', B: '#8e8672', h: '#8a3a32', H: '#5a2020', e: '#e03030' },
    rows: [
      '.k........k.',
      'khk......khk',
      'khHkkkkkkHhk',
      '.khHbbbbHhk.',
      '..kbbbbbbBk.',
      '.kbbbbbbbbBk',
      '.kbeebbeebBk',
      '.kbkkbbkkbBk',
      '..kbbBBbbBk.',
      '..kbkbkbkBk.',
      '...kBBBBBk..',
      '....kkkkk...',
    ],
  },
  rest: {
    pal: { k: '#0d0b10', y: '#f0d060', o: '#e07a20', r: '#a8341a', w: '#6a4a2a', W: '#3e2a18' },
    rows: [
      '.....k......',
      '....kyk.....',
      '...kyok.....',
      '...kyoyk....',
      '..kyoorrk...',
      '..kyorrrok..',
      '..koryyrok..',
      '..kkryyrkk..',
      '.kwWWooWWwk.',
      'kwwWWwwWWwwk',
      '.kWWkkkkWWk.',
      '..kk....kk..',
    ],
  },
  shop: {
    pal: { k: '#0d0b10', b: '#7a5a3a', B: '#4e3824', l: '#9a7a52', o: '#c9a54a', y: '#e8d080', s: '#b8a888' },
    rows: [
      '....kkkk....',
      '...kbsbbk...',
      '....kBBk....',
      '...klbbBk...',
      '..klbbbbBk..',
      '.klbbbbbbBk.',
      '.kbbbbbbbBkk',
      '.kbbbbbbBBky',
      '.kbbbbbBBBoy',
      '..kBBBBBBook',
      '...kkkkookk.',
      '.......kk...',
    ],
  },
  treasure: {
    pal: { k: '#0d0b10', w: '#7a5030', W: '#4e3220', l: '#9a6a40', o: '#c9a54a', O: '#8a6e2a' },
    rows: [
      '............',
      '..kkkkkkkk..',
      '.kllllllllk.',
      'klwwwwwwwwWk',
      'kowwwwwwwWok',
      'kooooOOoooOk',
      'kwwwwoowwwWk',
      'kwwwwOOwwwWk',
      'kowwwwwwwWok',
      'kWWWWWWWWWWk',
      '.kkkkkkkkkk.',
      '............',
    ],
  },
  event: {
    pal: { k: '#0d0b10', p: '#c8bca0', P: '#8a806a', q: '#5a2a2a' },
    rows: [
      '.kkkkkkkkkk.',
      'kpppppppppPk',
      '.kpppqqppPk.',
      '.kppqppqpPk.',
      '.kpppppqpPk.',
      '.kppppqppPk.',
      '.kpppqpppPk.',
      '.kpppppppPk.',
      '.kpppqpppPk.',
      'kpppppppppPk',
      '.kPPPPPPPPk.',
      '..kkkkkkkk..',
    ],
  },
  boss: {
    pal: { k: '#0d0b10', n: '#4a4458', N: '#2a2634', x: '#6e6880', e: '#e03030', o: '#8a6e2a' },
    rows: [
      '............',
      '.k...k...k..',
      'kxk.kxk.kxk.',
      'kxnkxnnkxnk.',
      'kxnnxnnnxnNk',
      'kxnnnnnnnnNk',
      'kxneNNeNNeNk',
      'kxnnnnnnnnNk',
      'kNNNNNNNNNNk',
      'koNoNoNoNoNk',
      '.kkkkkkkkkk.',
      '............',
    ],
  },
  item: {
    pal: { k: '#0d0b10', g: '#a8b8b8', c: '#8a2a3a', C: '#5a1a26', l: '#c84a5a', w: '#6a4a2a' },
    rows: [
      '.....kk.....',
      '....kwwk....',
      '....kggk....',
      '....kggk....',
      '...kgccgk...',
      '..kglccCgk..',
      '.kgcllcccgk.',
      '.kgccccCCgk.',
      '.kgcccCCCgk.',
      '..kgCCCCgk..',
      '...kggggk...',
      '....kkkk....',
    ],
  },
  book: {
    pal: { k: '#0d0b10', b: '#4a2a3a', B: '#2e1824', o: '#c9a54a', p: '#d8d0b8', P: '#a89e84' },
    rows: [
      '..kkkkkkkk..',
      '.kbbbbbbbbk.',
      'kobbbbbbbbpk',
      'kobbbobbbbpk',
      'kobbobobbbpk',
      'kobobbbobbpk',
      'kobbobobbbpk',
      'kobbbobbbbpk',
      'koBBBBBBBBpk',
      'koPPPPPPPPPk',
      '.koooooooook',
      '..kkkkkkkkk.',
    ],
  },
  weapon: {
    pal: { k: '#0d0b10', a: '#a8b0bc', A: '#6a7280', w: '#6a4a2a', o: '#c9a54a' },
    rows: [
      '.........kk.',
      '........kaak',
      '.......kaaAk',
      '......kaaAk.',
      '.....kaaAk..',
      '..k.kaaAk...',
      '.kokaaAk....',
      '..koaAk.....',
      '..kwok......',
      '.kwkkok.....',
      'kok..k......',
      '.k..........',
    ],
  },
  armor: {
    pal: { k: '#0d0b10', a: '#a8b0bc', A: '#6a7280', r: '#8c2a2e' },
    rows: [
      '.kkk....kkk.',
      'kaaAkkkkaAAk',
      'kaaaaAAaaAAk',
      'kaaaaaaaaAAk',
      '.kaaaaaaAAk.',
      '.kaaAaaAAAk.',
      '.kaaaAAAAAk.',
      '.krrrrrrrrk.',
      '.kaaAAAAAAk.',
      '..kAAAAAAk..',
      '...kkkkkk...',
      '............',
    ],
  },
  acc: {
    pal: { k: '#0d0b10', o: '#c9a54a', O: '#8a6e2a', y: '#e8d080', r: '#c03040', R: '#e87080' },
    rows: [
      '.....kk.....',
      '....krRk....',
      '...krrrRk...',
      '...korrok...',
      '..kookkook..',
      '.koyk..koOk.',
      '.kok...kOOk.',
      '.kook..kOOk.',
      '..koOkkOOk..',
      '...kOOOOk...',
      '....kkkk....',
      '............',
    ],
  },
  gold: {
    pal: { k: '#0d0b10', o: '#c9a54a', O: '#8a6e2a', y: '#e8d080' },
    rows: [
      '....kkkk....',
      '...kooook...',
      '..koyyyoOk..',
      '.koyyoOyoOk.',
      '.koyoyyOoOk.',
      '.koyoyyOoOk.',
      '.koyyOOoOOk.',
      '..koOOOOOk..',
      '...kOOOOk...',
      '....kkkk....',
      '............',
      '............',
    ],
  },
  pair: {
    pal: { k: '#0d0b10', a: '#a8b0bc', A: '#6a7280', o: '#c9a54a', O: '#8a6e2a' },
    rows: [
      '............',
      '..kkk..kkk..',
      '.kaaakkoook.',
      'kakkkaokkkOk',
      'ak.koaOk..kO',
      'ak.kokak..kO',
      'ak.kOkak.kOk',
      'Ak.kOAok.kOk',
      'kAkkkAOkkOk.',
      '.kAAAkkOOOk.',
      '..kkk..kkk..',
      '............',
    ],
  },
  job: {
    pal: { k: '#0d0b10', o: '#c9a54a', O: '#8a6e2a', y: '#e8d080', r: '#8c2a2e' },
    rows: [
      '.....kk.....',
      '....kyok....',
      '....koOk....',
      '.kkkyoOOkkk.',
      'kyoooorOOOOk',
      '.kooorrrOOk.',
      '..kooorOOk..',
      '..kooOOOOk..',
      '.kooOkkOOOk.',
      '.koOk..kOOk.',
      '..kk....kk..',
      '............',
    ],
  },
  floor: {
    pal: { k: '#0d0b10', p: '#c8bca0', P: '#8a806a', r: '#8c2a2e', g: '#6a7a50' },
    rows: [
      '.kkkk.kkkk..',
      'kpppPkpppPk.',
      'kppgPPppppPk',
      'kpgPPrppgPPk',
      'kppPPprpgPPk',
      'kppPPpprPPPk',
      'kpgPPppPPrPk',
      'kppPPpppPPrk',
      'kppPPrgpPPPk',
      'kpPPkppPPPk.',
      '.kkk.kkkkk..',
      '............',
    ],
  },
  blessing: {
    pal: { k: '#0d0b10', y: '#f0e0a0', o: '#c9a54a' },
    rows: [
      '.....k......',
      '..k.kyk.k...',
      '.kokkykkok..',
      '..kokokok...',
      '.kkkoookkk..',
      'kyyookooyyk.',
      '.kkkoookkk..',
      '..kokokok...',
      '.kokkykkok..',
      '..k.kyk.k...',
      '.....k......',
      '............',
    ],
  },
  skull: {
    pal: { k: '#0d0b10', b: '#d8d0b8', B: '#8e8672' },
    rows: [
      '...kkkkkk...',
      '..kbbbbbBk..',
      '.kbbbbbbbBk.',
      '.kbbbbbbbBk.',
      '.kbkkbkkbBk.',
      '.kbkkbkkbBk.',
      '.kbbbkbbBBk.',
      '..kbbbbbBk..',
      '..kbkbkbBk..',
      '...kBBBBk...',
      '....kkkk....',
      '............',
    ],
  },
  heart: {
    pal: { k: '#0d0b10', r: '#b02a34', R: '#6e161e', l: '#e06a70' },
    rows: [
      '............',
      '..kk...kk...',
      '.krrk.krrk..',
      'krllrkrrrRk.',
      'krlrrrrrrRk.',
      'krrrrrrrrRk.',
      '.krrrrrrRk..',
      '..krrrrRk...',
      '...krRRk....',
      '....kRk.....',
      '.....k......',
      '............',
    ],
  },
};
