// 自動生成ファイル（直接編集しない）。元は art/art_jobs.mjs・art/art_enemies.mjs。npm run build-art で作り直す。
// ドット絵の設計図（職業・敵）。'.' は透明、ほかの文字は pal の色。
// 仲間は正面向き、敵は左（仲間の側）向き。ボスは 24〜32 マスの大きな絵。

import { recolor, type Sprite } from './types';

/** 草原オオカミ */
const SHAPE_0: Sprite = {
  pal: { k: '#0d0b10', e: '#e03030', w: '#e8e2d0', g: '#4a4a58', G: '#2e2e3a', l: '#6a6a7c' },
  rows: [
    '................',
    '..k..k..........',
    '.klk.klk........',
    '.kggkggk........',
    'kgggggggk.......',
    'kgegggggGk......',
    'kgggggggggkkkkk.',
    'kwkwgggggggggGGk',
    '.kkkgggggggggGk.',
    '...kGgggglggGGk.',
    '...kGGggGGGggGk.',
    '...kGkGGk.kGGGk.',
    '...kGk.kGk.kGkk.',
    '...kk..kk..kk...',
    '................',
    '................',
  ],
};

/** 野ウサギ */
const SHAPE_1: Sprite = {
  pal: { k: '#0d0b10', b: '#6a5040', B: '#46342a', l: '#8a7058', e: '#e03030', w: '#d8d0c0', p: '#7a4a48' },
  rows: [
    '.......kk.kk....',
    '......kbbkbbk...',
    '......klpklpk...',
    '......klpklpk...',
    '.....kklbklbk...',
    '....klbbbbbbk...',
    '...klbbbbbbbk...',
    '..klbebbbbbbbkk.',
    '.klbbbbbbbbbbbbk',
    '.kbbbbbbbbbbbbBl',
    '.kBwbbbblbbbbbbl',
    '..kBbbbbbbbbBBBk',
    '...kBbbbbbbBBBBk',
    '...kBBkBBBkkBBBk',
    '..kBBkkBBk.kBBk.',
    '...kk..kk...kk..',
  ],
};

/** スライム */
const SHAPE_2: Sprite = {
  pal: { k: '#0d0b10', g: '#5a6a3a', G: '#3a4626', l: '#7a8a50', e: '#e0c840', E: '#d03030', w: '#d8d0b8', b: '#c8bfa8', r: '#5a2a2a' },
  rows: [
    '................',
    '................',
    '.........k......',
    '........kbk.....',
    '......kkbbk.....',
    '....kklgbglkk...',
    '...kllgggggllkk.',
    '..klgeggggEggglk',
    '.klgggggggggggGk',
    'klgEggggglgggGGk',
    'kgwrwrwgggggggGk',
    'kgrrrrrggggGgGGk',
    'kggwgwgggGGGGGGk',
    '.kGgGGgGGGGGGGGk',
    '.kGkGkkGGkkGkGGk',
    '..k.k..kk..k.kk.',
  ],
};

/** 大ガラス */
const SHAPE_3: Sprite = {
  pal: { k: '#0d0b10', c: '#2e2e3a', C: '#1e1e28', l: '#4a4a5e', y: '#6a6050', e: '#e03030' },
  rows: [
    '..........kkk...',
    '.........klllk..',
    '........klcCClk.',
    '.......klcCCCCk.',
    '...kk.klcCCCCCk.',
    '..kccklcCCCCck..',
    'kkceccccCCCck...',
    'yyccccccccccckk.',
    'kyycccccCCCCCcck',
    '.kkccccCCCCCCCcc',
    '...kcccCCCCCkcck',
    '....kcckkcCckkk.',
    '.....kykkykk....',
    '....kyykyyk.....',
    '.....kk.kk......',
    '................',
  ],
};

/** 氷柱コウモリ */
const SHAPE_4: Sprite = {
  pal: { k: '#0d0b10', b: '#4a5266', B: '#2e3444', l: '#6a7488', e: '#e03030', w: '#e8e8f0', i: '#a8d8f0', I: '#6aa0c8' },
  rows: [
    '................',
    '.....k....k.....',
    'k...kbk..kbk...k',
    'lk.kbbbkkbbbk.kl',
    'llkkbebbbbbbkkll',
    'lblkbbwbbbbbklbl',
    'lbbbbbbbbbbbbbbl',
    'BbbbbbbbbbbbbbbB',
    'BBbBbbbbbbbbBbBB',
    'BkBBBBbbbbBBBBkB',
    'kkikBkIBBIkBkikk',
    '.kIkkkikkikkkIk.',
    '..k..kIkkIk..k..',
    '......k..k......',
    '................',
    '................',
  ],
};

/** 炎の魔導師 */
const SHAPE_5: Sprite = {
  pal: { k: '#0d0b10', f: '#b89880', F: '#7a6050', e: '#f0e040', b: '#6a2418', B: '#401410', v: '#8a3a20', g: '#b0903a', y: '#f0a030', Y: '#fff080', r: '#c04a1a' },
  rows: [
    '.......kk.......',
    '......kbbk......',
    '.....kvbbBk.....',
    '....kvbbbbBk....',
    '...kvbBBBBbBk...',
    '..kYkvefeFbBk...',
    '.kyYykFfFFBBk...',
    '.kryrkvbgbbBk...',
    '..kfvvbbgbbbBk..',
    '..kvvbbbgbbbBk..',
    '..kvbbbbgbbbBk..',
    '..kvbbbbgbbbBBk.',
    '.kvbbbbbgbbbbBk.',
    '.kvbbbbbgbbbbBBk',
    '.kBBBBBBBBBBBBBk',
    '..kkkkkkkkkkkkk.',
  ],
};

export const JOB_SPRITES: Record<string, Sprite> = {
  '戦士': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', a: '#8a93a3', A: '#5a6170', S: '#3a3f4c', h: '#3a2a22', L: '#6b4a32', M: '#4a3222', u: '#7a6a58', w: '#5a4030', b: '#2e2018', o: '#b08a3a', r: '#8a3a32' },
    rows: [
      '.....kkkk..kkk..',
      '....khhhhkkaaak.',
      '...khhhhhhkaAAak',
      '...khffffhkaAAak',
      '...kfdffdfkkawk.',
      '...kfrfffFk.kwk.',
      '..kkkfFFFkkkkwk.',
      '.kuuuLLLLuuukwk.',
      'kuuuLLLLLLuuuwk.',
      'kffLLMLLMLLLffk.',
      'kffkLLLLLLkkkwk.',
      '.kkkbbbobbk.kwk.',
      '...kMMMMMMk.kwk.',
      '...kMMkkMMk..k..',
      '...kSSkkSSk.....',
      '....kk..kk......',
    ],
  },
  '騎士': {
    pal: { k: '#0d0b10', a: '#8a93a3', A: '#5a6170', r: '#8c2a2e', R: '#5e1a1e', o: '#c9a54a', f: '#d9b08c', d: '#2a2030' },
    rows: [
      '......kkkk......',
      '....kkaaAAkk....',
      '...kaaaaaAAAk...',
      '...kaaakkkkAk...',
      '...kakffffkAk...',
      '...kakfdkdfkk...',
      '...kaaffffkAk...',
      '....kkAAAAkk....',
      '..kkrrrrrrrrkk..',
      '.karrrrooorrrak.',
      '.karrrooooorrak.',
      '.kakrrrooorrkak.',
      '..k.kRrrrrRk.k..',
      '....kRRkkRRk....',
      '....kAkk.kAk....',
      '....kkk..kkk....',
    ],
  },
  '暗黒騎士': {
    pal: { k: '#0d0b10', n: '#3e3848', N: '#25212d', x: '#615872', e: '#e03030', p: '#4a2240', P: '#2e1428', a: '#8a93a3' },
    rows: [
      '...k......k.....',
      '..kxk....kxk....',
      '..kxxkkkkxxk....',
      '...kxxnnxxk.....',
      '...kxnnnnNk.....',
      '...kNeNNeNk.....',
      '..kknNNNNNkk....',
      '.kpxxNNNNxxpk...',
      'kppxnNnnNnxppkk.',
      'kppnNNeNNNnppkak',
      'kppNnNNNNnNppxak',
      'kPPNnnnnnnNPPkak',
      'kPPkNNNNNNkPPkak',
      'kPkkNNkkNNkkPkak',
      '.k.kxNkkxNk.k.k.',
      '....kk..kk......',
    ],
  },
  '侍': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', a: '#8a93a3', S: '#26242e', g: '#b0903a', r: '#7a2a2a', R: '#4e1a1c', s: '#4a3a4a' },
    rows: [
      '...k......k.....',
      '..kgk....kgk.k..',
      '...kgkkkkgk.kak.',
      '...kSggggSk.kak.',
      '..kSSSSSSSSkkak.',
      '...kSdffdSk.kak.',
      '..kkSffffSkkkak.',
      '.kRRRSFFSRRRkak.',
      'kRRRrrrrrrRRRgk.',
      'kfrRRRRRRRRrffk.',
      'kfkrrrrrrrrkkSk.',
      '.kkrRrRrRrRk.k..',
      '..kssssssssk....',
      '..kssskksssk....',
      '..kSSk..kSSk....',
      '...kk....kk.....',
    ],
  },
  '白魔道士': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', w: '#cfcabd', W: '#8e8a80', V: '#5e5a54', g: '#b0903a', s: '#5a4030' },
    rows: [
      '.kkk..kkkk......',
      'kgggkkwwwwk.....',
      'kgkgkwwwwwWk....',
      'kgggkwffffWk....',
      '.kskwfdffdWk....',
      '.kskwffffFWk....',
      '.kskwWffFWWk....',
      '.kskwwwgwwWWk...',
      '.kfwwwwgwwwWWk..',
      '.kswwwwgwwwWWk..',
      '.kskwwwgwwWWk...',
      '.kskwwwgwwWWk...',
      '.kskwwwgwwWWWk..',
      '.kskwwwgwwWWWk..',
      '.kskVVVVVVVVVk..',
      '..k.kkkkkkkkk...',
    ],
  },
  '黒魔道士': {
    pal: { k: '#0d0b10', f: '#b8a898', F: '#7e7068', d: '#1a1418', b: '#2e2a44', B: '#1c1a2c', v: '#4a4466', g: '#8e8a86', e: '#8a5ae0', E: '#c8a8ff', s: '#4a3a30' },
    rows: [
      '.....kbk........',
      '.....kvbk....k..',
      '....kvbbBk..kek.',
      '....kvbbbBkkeEek',
      '...kvbbbbbBkkek.',
      '...kvBffffBkksk.',
      '...kbfdffdBkksk.',
      '...kbFggggBkksk.',
      '..kvbbggggbBBfk.',
      '..kvbbbggbbbBsk.',
      '..kvbbbbbbbbBsk.',
      '..kvbbbbbbbbBsk.',
      '.kvbbbbbbbbbBsk.',
      '.kvbbbbbbbbbBsk.',
      '.kBBBBBBBBBBBsk.',
      '..kkkkkkkkkkkk..',
    ],
  },
  '赤魔道士': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', a: '#a8b0bc', r: '#8a2e30', R: '#5a1c20', h: '#3a2a22', g: '#b0903a', c: '#c8c0b0', S: '#2a2224', b: '#4a3a30' },
    rows: [
      '......kkkk......',
      '.....khhhhk.....',
      '....khhhhhhk....',
      '....khgggghk....',
      '....khdffdhk....',
      '....khffffFk....',
      '...krRfFFfRrk...',
      '..krrrRccRrrrk..',
      '.krrrrRcgRrrrrk.',
      'kbrrRrRccRrRrrk.',
      'kbbrRrRccRrRrfk.',
      'kbbrRrRccRrrRgk.',
      '.kRrrrRccRrrRak.',
      '.kRRrRRRRRRrRak.',
      '..kkSSkkSSkkkak.',
      '....kk..kk...k..',
    ],
  },
  '呪術師': {
    pal: { k: '#0d0b10', m: '#c8bfa8', M: '#8e8672', e: '#d03030', o: '#4a4a30', O: '#2e2e1e', q: '#6a6440', h: '#2a2420', b: '#d8d0b8', F: '#7a5a48', r: '#7a2a2a' },
    rows: [
      '....k.k..k......',
      '...khkhkkhk.....',
      '...khhhhhhhk....',
      '..khhmmmmmhhk...',
      '..khmemmmeMhk...',
      '..khmmmMmmMhk...',
      '..khhMkrkMhhk...',
      '.khkhMmmmMhkhk..',
      '.kqqoooooooqqk..',
      'kqqoooOoooOooqk.',
      'kboqoOooOoOqobk.',
      'kbkoOooooOookbk.',
      '.kqoOoOoOooOqk..',
      '.koOoOoOoOoOok..',
      '..kOkOkFFkOkOk..',
      '...k.k.kk.k.k...',
    ],
  },
  '盗賊': {
    pal: { k: '#0d0b10', f: '#d0a888', d: '#1a1418', a: '#8a93a3', c: '#3a4038', C: '#24281f', n: '#545a4c', L: '#4a3222', b: '#2a1e16', o: '#8a7a3a' },
    rows: [
      '......kkkk......',
      '.....kcccck.....',
      '....kccccnck....',
      '...kcccccccnk...',
      '...kcCdffdCck...',
      '...kcCCCCCCck...',
      '...kkcCCCCckk...',
      '..kncccLLcccnk..',
      '.knccLLLLLLccnk.',
      '.kfcCLLLLLLCcfk.',
      'kakcCbbobbbCckak',
      'kakcCCCCCCCCckak',
      '.k.kcCCkkCCck.k.',
      '...kCCk..kCCk...',
      '...kLLk..kLLk...',
      '....kk....kk....',
    ],
  },
  '狩人': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', g: '#4a5a38', G: '#2e3a24', l: '#6a7a50', w: '#6a4a2a', s: '#a8a090', q: '#7a5a3a', p: '#b8b0a0', L: '#4a3222' },
    rows: [
      '..k...kkkk......',
      '.kwk.kggggk.....',
      'kwkskggggglk....',
      'kwkskgGffffgk...',
      'wkkskgfdffdgk.k.',
      'wkkskgffffFgkkpk',
      'wkkskkgfFFgkkqpk',
      'wkksgggllgggqqk.',
      'wfkgglllllggqgk.',
      'wkfgGlLLLlGGgk..',
      'wkkfGllllllGfk..',
      'wkkskGllllGGk...',
      'kwkskGGllGGGk...',
      'kwkskGGkkGGk....',
      '.kwkkLLkkLLk....',
      '..k..kk..kk.....',
    ],
  },
  '錬金術師': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', h: '#5a4a3a', o: '#b08a3a', O: '#e0c070', t: '#3a5a5a', T: '#243c3c', L: '#7a5a3a', M: '#4e3824', v: '#7ab040', V: '#c8e080', g: '#a8b0b8' },
    rows: [
      '.....kkkkkk.....',
      '....khhhhhhk....',
      '...khhhhhhhhk...',
      '...koOohhoOok...',
      '...khffffffhk...',
      '...kfdffffdfk...',
      '...kkffFFffkk...',
      '..kttTffffTttk..',
      '.kttLLLLLLLLttk.',
      '.ktTLLMLLMLLTtk.',
      '.kffkLLLLLLkfgk.',
      '..kkkLLLLLLkgvgk',
      '....kLLMMLLkgVgk',
      '....kTTkkTTkkgk.',
      '....kMMkkMMk.k..',
      '.....kk..kk.....',
    ],
  },
  '吟遊詩人': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', h: '#6a4a2a', c: '#3a5a58', C: '#243a3a', y: '#a08a4a', Y: '#6a5a30', p: '#8a3a3a', w: '#7a5030', W: '#4a3020', s: '#c8c0a0', L: '#3a2a20' },
    rows: [
      '.....kkkkkpk....',
      '....kcccccpk....',
      '...kcccccccpk...',
      '..kccCCCCCCCk...',
      '...khffffffhk...',
      '...khfdffdfhk...',
      '...kkfffFffk....',
      '..kyyycFcyyyk...',
      '.kyyYccccYyyyk..',
      '.kyYcwwwwcYyyk..',
      '.kfYwWWWWwWffk..',
      '..kcwWsWWwcck...',
      '..kcCwwwwCcck...',
      '...kCCkkCCsk....',
      '...kLLkkLLk.....',
      '....kk..kk......',
    ],
  },
  '踊り子': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', h: '#4a2a2a', H: '#2e1a1c', r: '#8a3a4a', R: '#5a2232', g: '#b0903a', v: '#a87a8a', V: '#6e4a5a' },
    rows: [
      '.....kkgkk......',
      '....khhhhhk.....',
      '...khhhhhhhk....',
      '...khffffhhk....',
      '..khhdffdfhhk...',
      '..khhffffFhHk...',
      '.khhHkfFFHhHk...',
      '.khHkffffffHHk..',
      'kvfkgrrrrrgfkvk.',
      'kvkfkffffFfkkvk.',
      'kvkkkffFFfk.kvk.',
      '.kvkggrrrggkvk..',
      '..kvvrRrRrvvk...',
      '...kVrRrRrVk....',
      '....kffkffk.....',
      '.....kk.kk......',
    ],
  },
  '召喚士': {
    pal: { k: '#0d0b10', f: '#d0a888', F: '#9a7258', d: '#1a1418', h: '#c8bca0', H: '#8a806a', p: '#3a2e4a', P: '#241c30', q: '#5a4a6e', g: '#40b0a0', G: '#a0f0e0', o: '#b0903a' },
    rows: [
      'khk........khk..',
      'khhk.kkkk.khhk..',
      '.kHhkppppkhHk...',
      '..kHpppppphk....',
      '...kpPffffpk....',
      '...kpfdffdpk....',
      '...kpffffFpk....',
      '..kqqpfFFpqqk...',
      '.kqqppopoppqqk..',
      'kqqpppooopppqk..',
      'kfgpppoPopppfgk.',
      'kgGgkppopppkgGgk',
      '.kgkkppoPpPkkgk.',
      '..kkpppPppPPkk..',
      '...kPPPPPPPPk...',
      '....kkkkkkkk....',
    ],
  },
};

export const ENEMY_SPRITES: Record<string, Sprite> = {
  'スライム': SHAPE_2,
  '野ウサギ': SHAPE_1,
  '大ガラス': SHAPE_3,
  '毒キノコ': {
    pal: { k: '#0d0b10', p: '#6a3a5a', P: '#3e2238', s: '#a89878', w: '#a8a090', W: '#6e6858', e: '#e0d040', r: '#4a2a2a', t: '#d8d0b8', g: '#8aa040' },
    rows: [
      '...k.......k....',
      '..kgkkkkkkkgk...',
      '...kkppppppk..k.',
      '..kpppspppppkkgk',
      '.kppppppppspppk.',
      'kppsppppppppppPk',
      'kpppppppsppppPPk',
      'kPPppppppppPPPPk',
      '.kPPPPPPPPPPPPk.',
      '..kwewweWWWWkkk.',
      'k.kwwwwwwWWWkkgk',
      'gkkrtrtrwWWWk.k.',
      'k.krrrrrwWWWk...',
      '..kwwwwwwwWWk...',
      '.kWWWWwwWWWWWk..',
      '..kkkkkkkkkkk...',
    ],
  },
  '草原オオカミ': SHAPE_0,
  '雪狼': recolor(SHAPE_0, { g: '#a8aebc', G: '#6a7084', l: '#d0d4e0', e: '#e8c030' }),
  '野盗': {
    pal: { k: '#0d0b10', f: '#c8a080', d: '#1a1418', h: '#5a4a38', H: '#3a3024', r: '#6a2a2a', L: '#5a4030', b: '#2a1e16', o: '#b08a3a', a: '#a8b0bc', A: '#6a7280', S: '#2a2224', g: '#8a7a3a', G: '#5a4e26' },
    rows: [
      '.....kkkkk......',
      '....khhhhhk.....',
      '...khhhhhhHk....',
      '...khffffhHk....',
      '...kfdffhhHk....',
      '...krrrrrhHk....',
      '...kkrrrrHk.....',
      '..kLLLrLLLLk....',
      'kkLLLLLLLLLLk...',
      'aAfLLLLLLLLLfk..',
      'kkkkLbbobLLkgGk.',
      '...kHHHHHHkkGGGk',
      '...kHHkkHHkkGGk.',
      '...kHHkkHHk.kk..',
      '..kSSkkSSk......',
      '...kk..kk.......',
    ],
  },
  '森の大熊': {
    pal: { k: '#0d0b10', b: '#4a3a30', B: '#2e241e', l: '#6a5444', e: '#e03030', w: '#d8d0c0', r: '#6a2222', s: '#8a6a5a', n: '#1a1418' },
    rows: [
      '....................',
      '....................',
      '.........kkkk.......',
      '.......kkllllkk.....',
      '...kk.kllbbbbllkk...',
      '..kllklbbbbbbbbllk..',
      '.klbblbbbbbbbbbbblk.',
      '.klbbbbbbbbbbbbbbbBk',
      'klbebbbbbbsbbbbbbbBk',
      'klbbbbbbbbbsbbbbbbBk',
      'nbbbbbbbbbbbsbbbbBBk',
      'krwrwbbbbbbbbbbbbBBk',
      '.krrrBbbbbbbbbbbBBBk',
      '..kBbbbBbbbbbbbBBBBk',
      '..kbbbBBkBbbbbBBbbBk',
      '..kbbbBk.kBbbBkBbbBk',
      '.kbbbbBk.kBbbBkBbbBk',
      '.kwwwBBkkwwbBkwwBBk.',
      '..kkkkk..kkkk.kkkk..',
      '....................',
    ],
  },
  '野盗の用心棒': {
    pal: { k: '#0d0b10', f: '#b08868', F: '#7a5a44', d: '#1a1418', s: '#d8c0a8', L: '#4a3424', M: '#2e2018', u: '#6a5a48', w: '#5a4030', W: '#3a2a1e', a: '#8a93a3', r: '#6a2a2a', b: '#2a1e16', o: '#b08a3a' },
    rows: [
      '............k.k.....',
      '......kkkk.kakak....',
      '.....kffffkkwWwak...',
      '....kffffffkawWwk...',
      '....kfdffsFkwWwak...',
      '...kffffsfFkawWk....',
      '....krrfFFFkkWk.....',
      '...kkkfFFFkkkWk.....',
      '..kuuuLLLLuuuWk.....',
      '.kuuLLLLLLLLufWk....',
      'kffLLMLLLLLLLffFk...',
      'kffLLLMLLLLLLFFk....',
      'kffuLLLMLLLLLkk.....',
      '.kFkbbbobbbbbk......',
      '..kkMMMMMMMMMk......',
      '...kMMMMkMMMMk......',
      '...kMMMk.kMMMk......',
      '..kWWWWkkWWWWk......',
      '...kkkk..kkkk.......',
      '....................',
    ],
  },
  '草原の主（大角獣）': {
    pal: { k: '#0d0b10', b: '#5a4632', B: '#3a2c20', m: '#3e2e20', M: '#261c12', l: '#8a7252', h: '#c8bca0', H: '#8a806a', e: '#f0c030', E: '#e03030', n: '#1a1418', w: '#d8d0c0', s: '#9a7a5a', r: '#6a2a20' },
    rows: [
      '........................',
      '........................',
      '........................',
      '..k.....................',
      '.khk......k....kkkk.....',
      'khHk.....kHk.kkmmmmkk...',
      'khHk....kHHkkmmmmmmmmkk.',
      'khHkk..kHHkkmmmmmmmmmmbk',
      '.khhHk.kHkmmmmmmmmmmmbbk',
      '..khhHkmmmmmmmmmMmmmbbBk',
      '...khhmmmmmmmmmMbbbbbbBk',
      '..kllmmmmmmmmMMbbbbbbbBk',
      '.klbbeEmmmmmMbbbbbsbbbBk',
      'klbbbmmmmmmMbbbbbbsbbbBk',
      'kbbbbbmmmmMbbbbbbbbsbBBk',
      'nbbbbbbmmMbbbbbbbbbbBBBk',
      'nbbbbbbbMbbbbbbbbbbbBBBk',
      'krwbbbbMMbbbbbbbbbbBBBk.',
      '.kBbbbMMBBbbbBBBBBBBBBk.',
      '..kBBkMbBkBbbBkkBbbBbBk.',
      '...kkkbbBkBbbBkkBbBkbbBk',
      '.....kbbBkkbbBkkBbBkbbBk',
      '....kHHHBkHHHBkHHHBkHHBk',
      '.....kkkk.kkkk.kkkk.kkk.',
    ],
  },
  '腐肉の蠅群': {
    pal: { k: '#0d0b10', b: '#4e5a26', B: '#2c3416', m: '#8a9a3a', w: '#8a9496', W: '#5a6466', e: '#e03030', o: '#5a3a28', O: '#3a2418', r: '#7a3a32', c: '#c8bca0' },
    rows: [
      '.kk.............',
      'kwwk.....k......',
      'wWwk....kwk.kk..',
      'ebmbk..kwWwkwwk.',
      'kbBBk.kwwwWwWwwk',
      'kBkBkkmbbwWwbwk.',
      '.k.kkebmbbbbbBk.',
      '....kbbbBbBbBBBk',
      '..kk.kBbBbBbBBk.',
      '.kwwk.kBkBkBkkk.',
      'kwWwk..k.k.k.kwk',
      'ebmbBkkkk...kwWw',
      'kBbBkkorokkkebmb',
      '.kkkooOrrOokkBbB',
      '..korcrrcrrOkkkk',
      '.kOOOOOOOOOOOk..',
    ],
  },
  '墓荒らし': {
    pal: { k: '#0d0b10', g: '#5e5648', c: '#4a443a', C: '#2c2822', d: '#141016', e: '#e0c040', f: '#8a7a68', a: '#9a6a3a', A: '#5a3a22', h: '#5a4030', l: '#f0c050', L: '#3a3030', n: '#1e1a18' },
    rows: [
      '..kkk...........',
      '.kaaak..........',
      'kaAAAak.........',
      'aAkkkAk.kkkk....',
      'ak..khkkcccck...',
      'ak..khkcgggcCk..',
      'kak.khccdddcCCk.',
      '.k..khcdedecCCCk',
      '...kffcdddcCCCCk',
      '...kffccccCcCCCk',
      '....khcccCcCCCCk',
      '....khcCcCCCCCk.',
      '....khkCCcCCCkLk',
      '.....kCCkkCCkLlL',
      '....knnkknnkkLlL',
      '.....kk..kk..kLk',
    ],
  },
  '首吊りカカシ': {
    pal: { k: '#0d0b10', p: '#4a3a2a', P: '#2e241a', s: '#8a7a58', S: '#5e523a', e: '#f0c030', d: '#1a1418', r: '#a08a5a', c: '#4a3a4a', C: '#2e2430', y: '#a89848', h: '#3a3028', H: '#241e18', f: '#1e1e28' },
    rows: [
      '......khhk......',
      '....kkhhhHkk....',
      '...khhhhhhhHk...',
      '....kksssSkk....',
      '.....keseSk.....',
      '.....kdsdSkk....',
      'k.kkkkkrrrkrkkk.',
      'ykcccccrcccrkcyk',
      'yppcCccccCcrpPPy',
      'kkfkcccCcccrkfkk',
      '..kkcCcCcCcCkk..',
      '....kyckyckyk...',
      '.....kkpPk.k....',
      '......kpPk......',
      '.....kPpPPk.....',
      '......kkkk......',
    ],
  },
  '牙イノシシ': {
    pal: { k: '#0d0b10', x: '#6a4a40', b: '#3e3428', B: '#241e18', l: '#5a4c3a', m: '#16120e', t: '#e0d8c0', T: '#a89e86', e: '#ff3020', n: '#7a5a50', h: '#1a1418' },
    rows: [
      '................',
      '........k.k.k...',
      '......kkmkmkmkk.',
      '....kkmmmmmmmmmk',
      '...klmmbmbmbmmmm',
      '..klbbbbbbxbbbmB',
      'kklbebbbbbbxbbbB',
      'tklbbbbbbbbbbbBB',
      'tnbbbbbbbbbbbBBB',
      'tnnTbbbbbbbbBBBk',
      'kttTBbBBbbbBBBBk',
      '.kkkBbBkBbbBBBk.',
      '...kBBk.kBBkBBk.',
      '..khhk.khhkkhhk.',
      '...kk...kk..kk..',
      '................',
    ],
  },
  '雪ウサギ': recolor(SHAPE_1, { b: '#c4c8d2', B: '#8a90a2', l: '#e4e8f0', p: '#b8a0b0', e: '#e03030' }),
  '氷の精': {
    pal: { k: '#0d0b10', i: '#9ac8e0', I: '#5a88a8', j: '#3a5a7a', w: '#e0f0ff', e: '#60e0ff', d: '#1a2a40', s: '#c8e8ff' },
    rows: [
      '........k.......',
      '.......kwk......',
      '...k..kwik......',
      '..kskkwiiIk..k..',
      '...k.kwiiIk.ksk.',
      '....kwiiiIIk.k..',
      '...kwjiiijIIk...',
      '..kwiieiieIIjk..',
      '..kwiiiiiiIIjk..',
      '.k.kwdwdwdIjk...',
      'ksk.kiiiiIjk.k..',
      '.k..kIiiIIjkksk.',
      '.....kIIIjk..k..',
      '....k.kIjk......',
      '...kskkjk.......',
      '....k..k........',
    ],
  },
  '凍った亡者': {
    pal: { k: '#0d0b10', f: '#7a8a98', F: '#52606e', G: '#384450', e: '#60d0ff', r: '#3e3a4a', R: '#28252f', i: '#c8e8ff', I: '#8ab8d8', t: '#c8c0a8' },
    rows: [
      '.....k...k......',
      '....kikkkik.....',
      '....kffffiIk....',
      '...kfFffffFk....',
      '...keFffffFk....',
      '...kfffffFFk....',
      '...kttGfFFFk....',
      'kkkrrGGFFFrrk...',
      'ffkrrrrrrrrrrk..',
      'kFfffrrrrrrrrrk.',
      '.kkffRrrrrrRrk..',
      '...kRrrRrrRRrk..',
      '...kRrRRkRrRRk..',
      '...kfFkkkfFkk...',
      '..kIIiikiIIIk...',
      '...kkkk.kkkk....',
    ],
  },
  '氷柱コウモリ': SHAPE_4,
  '雪原の小鬼': {
    pal: { k: '#0d0b10', g: '#6a7a5a', G: '#46523a', e: '#e0c040', w: '#d8d0c0', u: '#c8c4bc', U: '#8a8680', c: '#5a4030', C: '#3a2a1e', s: '#6a7280', S: '#454b58', o: '#a08a5a' },
    rows: [
      '.....kkkk.......',
      '....kuuuuk......',
      '...kuuuuuUk.....',
      '..kuggggguUk.k..',
      '.kgeggggGuUkkck.',
      '.kgggggGGuUkcCk.',
      '..kwgwgGGUkkcCk.',
      '.kssssuUUUkgCk..',
      'ksSoSsUUuUgGk...',
      'ksSoSSsUUUUk....',
      'ksSoSsUUUUk.....',
      'kssSsCCCCCk.....',
      '.ksskGGkGGk.....',
      '..kkkGGkGGk.....',
      '...kCCkkCCk.....',
      '....kk..kk......',
    ],
  },
  '雪男': {
    pal: { k: '#0d0b10', w: '#c8ccd8', W: '#8a90a4', V: '#5e6478', f: '#5a7088', F: '#3a4a60', e: '#e03030', t: '#e8e4d8', r: '#4a2030', c: '#2a3040' },
    rows: [
      '.......kkkkkk.......',
      '......kwwwwwwk......',
      '.....kwwwwwwwWk.....',
      '....kwwffffwwWWk....',
      '...kwwfefffwwWWWk...',
      '..kkwfffffFwwWWWWk..',
      '.kwwwrtrtFFwwWWWWWk.',
      'kwwwwrrrrFwwwWWWWWWk',
      'kwwwwwtwtwwwwWWWWWWk',
      'wwWwwwwwwwwwwWWWWWWV',
      'wWWwwwwwwwwwWWWWWWVV',
      'wWWkwwwwwwwWWWWWkWVV',
      'wWWkwwwwwwWWWWWWkWVV',
      'fcfkWwwwwwWWWWWVkVVV',
      'fFfkWWwwwWWWWWVVkFcF',
      'kkkkWWWWWkWWWWVVkkkk',
      '...kWWWWk.kWWWVVk...',
      '..kWWWWWk.kWWWVVVk..',
      '..kffffk..kffFFkk...',
      '...kkkk....kkkk.....',
    ],
  },
  '氷の魔術師': {
    pal: { k: '#0d0b10', f: '#a8b0c0', F: '#6e7888', e: '#80e0ff', b: '#2e4a6a', B: '#1c2e46', v: '#4a6e94', c: '#c8e8ff', C: '#80b8e0', g: '#a8b8c8', s: '#4a5a6a' },
    rows: [
      '.......kck....k.....',
      '......kcCck..kck....',
      '.....kcbbbckkcCck...',
      '....kcbbbbbckkCk....',
      '....kbbbbbbbBkck....',
      '...kvbBffffBBksk....',
      '...kvbfeffeFBksk....',
      '...kvbfffffFBksk....',
      '...kvbBFggFBBksk....',
      '..kvvbbbggbbBfsk....',
      '.kvvbbbbggbbBBsk....',
      '.kvbbbbcggbbbBsk....',
      '.kvbbbbCbbbbbBsk....',
      'kvbbbbbcbbbbbBsk....',
      'kvbbbbbCbbbbbbBsk...',
      'vbbbbbbcbbbbbbBBsk..',
      'vbbbbbbCbbbbbbBBBsk.',
      'BBcBBBBcBBBcBBBBBBk.',
      'kckkkCkkkkckkkCkkk..',
      '.k...k....k...k.....',
    ],
  },
  '氷の女王': {
    pal: { k: '#0d0b10', c: '#c8e8ff', C: '#80b8e0', j: '#4a7aa8', f: '#c0c8d4', F: '#8a94a8', e: '#80f0ff', h: '#a8c0d8', H: '#6a84a0', g: '#2a4a6e', G: '#1a3050', v: '#4a6e94', r: '#3a2a4a', w: '#e8f4ff' },
    rows: [
      '.....k....kcck....k.....',
      '....kck..kcCCck..kck....',
      '....kcCkkcCCCCckkCck....',
      '.....kcCcCCccCCcCck.....',
      '.....kcjjjjjjjjjjck.....',
      '....khhhhhhhhhhhhhhk....',
      '...khhHffffffffffHhhk...',
      '...khHffeeffffeeffHhk...',
      '..khhHfffffkkfffffHhhk..',
      '..khHHFffFFFFFFffFHHhk..',
      '.khhHkFFrrrFFrrrFFkHhhk.',
      '.khHHkgvFFFFFFFFvgkHHhk.',
      '.khHkgvvggggggggvvgkHhk.',
      'khhHgvwgggGggGgggwvgHhhk',
      'khHkgvgggggGGgggggvgkHhk',
      'khHCgvvggGggggGggvvgCHhk',
      '.kCkgvggggGGGGggggvgkCk.',
      '..kgvvgggggGGgggggvvgk..',
      '..kgvggggGgGGgGggggvgk..',
      '.kgvvggggGGGGGGggggvvgk.',
      '.kgvgggggGGggGGgggggvgk.',
      'kgvvggggGGGGGGGGggggvvgk',
      'kcCcCcCcCcCccCcCcCcCcCck',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
    ],
  },
  '霜の亡霊': {
    pal: { k: '#0d0b10', g: '#a8c0d0', G: '#6a8498', l: '#d8e8f0', d: '#141822', e: '#80f0ff', i: '#e8f8ff', w: '#5a7088' },
    rows: [
      '......kkkk......',
      '.....kllllkk....',
      '....klgggglGk...',
      '...klgggggggGk..',
      '...kgddggddgGk..',
      '...kgdeggdegGk..',
      '...kggggggggGGk.',
      '..klggdddggGGGk.',
      '.klggdddddgGGGwk',
      'kikgggdddgGGGGww',
      'iglkggggGGGGGwkk',
      'kikkgGgGGGGwwwk.',
      '.k.kGgGGwGwwwk..',
      '....kkGwkwwwk...',
      '......kk.kwwk...',
      '..........kk....',
    ],
  },
  '氷蜘蛛': {
    pal: { k: '#0d0b10', b: '#3a4a5e', B: '#222c3a', l: '#5a7088', i: '#a8d8f0', I: '#6aa0c8', j: '#e8f8ff', e: '#60f0ff' },
    rows: [
      '................',
      '..k.........k...',
      '.kjk.......kjk..',
      '.kiik.kkk.kiIk..',
      '.kIkiklllkikIk..',
      'kik.kIblbbblkIk.',
      'kIkkIbbbbbbbbIk.',
      'ikkeebbbbbbbbbIk',
      'IkebebbbbblbbbbI',
      'kkBbbbbbbbbbbbBk',
      'kIIBBbbbbbbbbBBI',
      'IkkkIBBBBBBBBkkI',
      'IkkIkkIkkkIkkkIk',
      'kkIkkIk..kIkkIk.',
      'kjkkjk....kjkkjk',
      '.k..k......k..k.',
    ],
  },
  '凍てつく骸骨弓兵': {
    pal: { k: '#0d0b10', h: '#c8c4b4', H: '#8a8676', i: '#d8f0ff', I: '#8ac0e0', c: '#3a5a7a', C: '#243a52', e: '#60e0ff', d: '#141418', w: '#5a4a3a', W: '#3a2e22', s: '#a8a090', a: '#8a93a3' },
    rows: [
      '..kwkkiiik......',
      '.kwWkhhhhik.....',
      '.kwkhhhhhhHk....',
      'kwksdedhdhHk....',
      'kwkskhhhhHk.....',
      'kwkskhdhdcck....',
      'wkksahhccccCk...',
      'wakahhhHhcCCck..',
      'wkkskchHhCcCCk..',
      'kwkskcHhHCcCck..',
      'kwkskkCcCcCcCk..',
      'kwksk.khcHCkk...',
      '.kwWk.khkkHk....',
      '..kwk.khkkHkk...',
      '...k.kiIhkiIHk..',
      '......kkk.kkk...',
    ],
  },
  '吹雪の鷲': {
    pal: { k: '#0d0b10', w: '#d8dce4', W: '#9aa2b0', g: '#5e6678', b: '#d8b040', e: '#e8c030', i: '#a8e0ff', I: '#6ab0e0', t: '#3a3a44' },
    rows: [
      'kik...........ki',
      'kIik.........kiI',
      '.kWik.......kiWk',
      '.kWWik.....kiWWk',
      '..kWWwk...kwWWgk',
      '..kgWWwkkkwWWgk.',
      '...kgWWwwwWWgk..',
      '....kgWwwwWgk...',
      '....kkwwwWWgk...',
      '...kwwwwgWWk....',
      '..kwwewwWgk.....',
      '.kbbwwwWWgk.....',
      '.kbkwwWWtgk.....',
      '..k.kkktktk.....',
      '.......k.k......',
      '................',
    ],
  },
  '火トカゲ': {
    pal: { k: '#0d0b10', r: '#8a3a20', R: '#5a2414', l: '#b05a2a', y: '#e8a030', Y: '#f0e070', e: '#f0e040', w: '#d8d0c0' },
    rows: [
      '................',
      '................',
      '................',
      '.............k..',
      '............kYk.',
      '..kkk.......kyYk',
      '.klllk.k.k.kyyyk',
      'kleRrlklklklyyk.',
      'lrrrrrrlrlrrrryk',
      'wkwrrrrrrrrrrRRk',
      'kRRRRrrrrrrrRRk.',
      '.kkRRRRRRRRRRk..',
      '..kRkRRkkkRRRk..',
      '.kRRkkRRkkRkRRk.',
      '..kk..kk..k.kk..',
      '................',
    ],
  },
  '溶岩スライム': recolor(SHAPE_2, { g: '#a8401a', G: '#5a1e10', l: '#e8862e', e: '#fff080', E: '#ffd040', w: '#e8d0a0', b: '#2e2626', r: '#2a1010' }),
  '火の鳥': recolor(SHAPE_3, { c: '#c04a1a', C: '#7a2a10', l: '#f0a030', y: '#f0d060', e: '#fff080' }),
  '岩ゴーレム': {
    pal: { k: '#0d0b10', s: '#6a6258', S: '#4a443c', t: '#2e2a26', l: '#8a8276', e: '#e0c040' },
    rows: [
      '....kkkk........',
      '...klllskk......',
      '..klsssssSk.....',
      '..kseSssSSk.....',
      '..ksssssSSkkk...',
      '.kllsSSSSlllsk..',
      'klssstsssssssSk.',
      'kssSsssstssSSSk.',
      'ksSSksstsssSSSSk',
      'ksSSkssssssSkSSk',
      'lssSkSSsSSSSksSS',
      'sSSSksskksSSkSSS',
      'kkkkksskksSSkkkk',
      '...klsskksSSSk..',
      '...kSSSkkSSSSk..',
      '....kkk..kkkk...',
    ],
  },
  '火山コウモリ': recolor(SHAPE_4, { b: '#5a2a26', B: '#36181a', l: '#8a3a2a', e: '#f0e040', i: '#f0a030', I: '#c04a1a' }),
  '炎の魔導師': SHAPE_5,
  '溶岩ゴーレム': {
    pal: { k: '#0d0b10', s: '#3a2e2a', S: '#241c1a', l: '#5a4a42', y: '#f0a030', Y: '#fff080', r: '#c04a1a', e: '#fff080' },
    rows: [
      '.......kkkkk........',
      '......kllllsk.......',
      '.....klsssssSk......',
      '....klsYeyssSSk.....',
      '...kkssyrsrsSSkkk...',
      '..kllssssssSSSllsk..',
      '.klssssrsssssSSSSSk.',
      'klsssSsyrssSssSSSSSk',
      'kssSSssrYrsSsSSSSSSk',
      'kssSSkssryssSkSSSSSk',
      'kssSSksssrssSkSSrSSk',
      'lssrSkssssrsSkSrySSk',
      'ssrySkSsssyrSkSSrSSk',
      'sryYskSSSSSSSkSSSSSk',
      'SSSSkkssSkkssSkkSSk.',
      'kkkkklssSkkssSSkkk..',
      '....ksrySkksyrSk....',
      '....kssSSkkssSSSk...',
      '...kSSSSSkkSSSSSk...',
      '....kkkkk..kkkkk....',
    ],
  },
  'サラマンダー': {
    pal: { k: '#0d0b10', r: '#9a3a1a', R: '#5e2010', l: '#c8602a', y: '#f0a030', Y: '#fff080', e: '#fff080', w: '#e8e0c8', m: '#3a1008' },
    rows: [
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '.........k..k.......',
      '........kykkyk.k....',
      '.......kyYyyYykyk...',
      '...kkkkyyyyyyyyYyk..',
      '..klllklrrrrrrryyk..',
      '.klerrlrrrrrrrrrryk.',
      'klrrrrrrrrrrrrrrrryk',
      'lrrrrrrrlrrrrrrrRRyY',
      'mwmwrrRrrrrrrrrRRRRy',
      'kmmmmRRrRRrrrrRRRRkk',
      'wkwkkRRrRRRRRRRRRRk.',
      'k.k.krRkRRkkkRRkRk..',
      '...krrkkRRkkrRkkRRk.',
      '..kwwkkwwkkwwk.kwwk.',
      '...kk..kk..kk...kk..',
    ],
  },
  '炎竜': {
    pal: { k: '#0d0b10', p: '#b8783a', P: '#7e4e26', r: '#8a2a1a', R: '#561810', l: '#b04a24', m: '#3a0e08', h: '#c8bca0', H: '#8a806a', e: '#fff060', w: '#e8e0c8', o: '#e06020', b: '#6a3a2a' },
    rows: [
      '................................',
      '......................kk........',
      '.....................kRRkk......',
      '....................kRRRRRkkk...',
      '....................kRbbRRRRRkk.',
      '...................kRbbbRbbbRRRk',
      '..........kk.......kRbbbRbbbbbRk',
      '.........khhk.....kRbbbbRbbbbbRk',
      '....kkk.khHk.....kkRbbbRbbbbbbRk',
      '...klllkhHk.....kRRbbbbRbbbbRRRk',
      '..klrrrrhrk.....kRbbbbRbbbbbRkk.',
      '.klrrerrrrrk...kRbbbbRbbbbbRk...',
      'klrrrrrrrrrrk..kRbbbRbbbbbRk....',
      'lrrrrrrrrrrrrkkRbbbbRbbbbRk.....',
      'mwmwmwrrrrrrrlkRbbbRbbbbRk......',
      'kmmmmoorrrrrrrlRbbbbRbbbRk......',
      'wmwmwRRRrrrrrrrRbbbRRRRRk.......',
      'kRRRRRkkRRrrrrrrrllkkkkk........',
      '.kkkkk..kRRrrrrrrrrrllkk........',
      '.........kRRpprrrrrrrrrlk.......',
      '.........kRppPrrrrrrrrrrlk......',
      '.........kRpPprrrrrrrrrrrlk.....',
      '..........kpPprrrrrrrrrrrrlk....',
      '..........kRPprrrrrrrrrrrrrlkk..',
      '..........kRRrrrrRRrrrrrrrrRrrk.',
      '..........krrRRRRrRRRRrrrrRRrrrk',
      '.........krrrRkkkkRRRrrRRkkRRrrk',
      '........krrrRk...kRrrrRkk..kRRrk',
      '........krrRk....kRrrRk.....kRrk',
      '.......kwwRRk...kwwRRk.....kRrk.',
      '........kkkk.....kkkk.....kRRk..',
      '...........................kk...',
    ],
  },
  '火吹き小鬼': {
    pal: { k: '#0d0b10', s: '#2a2426', S: '#18141a', l: '#4a3a38', e: '#ffd040', h: '#8a7a6a', f: '#f0a030', F: '#c04a1a', y: '#fff080', o: '#e8602a', w: '#5a2a26', W: '#3a1a18', t: '#2a2426' },
    rows: [
      '......k...k.....',
      '.....khk.khk....',
      '.....khhkhhk.k..',
      '......ksssskkwk.',
      'k.k..ksesssSwwk.',
      'ykFkkssssssSwWk.',
      'fyfFFossssSwwWk.',
      'kfyfFoosssSSwWk.',
      '.kFkkkssSSSkWk..',
      '..k.klsoSsSSk...',
      '...kssksosSSk...',
      '....klkssSSSk.k.',
      '.....ksSkksSkktk',
      '....kSSkkSSkkttk',
      '.....kk..kkktkk.',
      '............k...',
    ],
  },
  '黒曜の蠍': {
    pal: { k: '#0d0b10', o: '#2a2430', O: '#16121a', l: '#5a4e6a', s: '#ff8a20', S: '#ffd060', e: '#ff6020' },
    rows: [
      '......kkk.......',
      '.....kSsSk......',
      '......kssk......',
      '.......koOkk....',
      '........koOok...',
      '.kkk.....koOOk..',
      'kllok.....koOk..',
      'lokkk..kkkloOk..',
      'lk.kokkloooOOkk.',
      'lokoOoeoooooooOk',
      'kooOooooooolooOo',
      '.kkOkoOoOoOoOOkk',
      '...kOkOkOkOkOk..',
      '....k.k.k.k.k...',
      '................',
      '................',
    ],
  },
  '溶岩の大蛇': {
    pal: { k: '#0d0b10', s: '#3a2420', S: '#22140f', c: '#f08a20', e: '#fff080', f: '#e8d8b8', t: '#c02020', l: '#5a3428' },
    rows: [
      '................',
      '...kkk..........',
      '..ksssk.........',
      '.ksesSsk........',
      'ktsfsSSsk.......',
      'tkfksSSsk.......',
      'k.kklsSsk.......',
      '....ksSskkk.....',
      '...klsSSksskk...',
      '..ksscsSsscSsk..',
      '.kssSsscSsSsSsk.',
      'klscSsSsscSssSsk',
      'ksSsssccsSsssSSk',
      '.kSSsSsSSsSsSSk.',
      '..kSSSSSSSSSSk..',
      '...kkkkkkkkkk...',
    ],
  },
  '燃えさかる骸': {
    pal: { k: '#0d0b10', b: '#2e2220', B: '#1a1210', g: '#c04a1a', f: '#f08a20', F: '#c03a10', y: '#ffe070', e: '#fff080', h: '#a89878' },
    rows: [
      '.....kykfkk.....',
      '....kfyFfkyk....',
      '...kfFyffFfkk...',
      '....kFbbbbFkfk..',
      '...kfbebbBbFfk..',
      '...kFbbbbBBfk...',
      '..kkkbhbhBFkk...',
      '.khbbbbbgbBBfk..',
      'khkbbgbbbbBBFk..',
      '.k.kbbbgbBBbBk..',
      '...kbBbbbBBfk...',
      '...kbbBkbBBk....',
      '...kbBkkbBk.....',
      '..kfbBkFbBk.....',
      '.kFfFfFfFfFk....',
      '..kkkkkkkkk.....',
    ],
  },
  '魔族の兵士': {
    pal: { k: '#0d0b10', a: '#8a93a3', A: '#5a6170', S: '#4e1e2a', s: '#7a3040', h: '#b8ac94', e: '#f0d040', n: '#3a3444', N: '#24202c', x: '#5a5266', r: '#6a1a22' },
    rows: [
      '...k......k.....',
      '..khk....khk....',
      '..khhkkkkhhk....',
      '...khnnnnhk.....',
      '...kxnnnnNk.....',
      '...keSsssNk.....',
      '...kSssSsNk.....',
      '..kkNSSSNNkk....',
      '.kxxnnnnnnxxk...',
      'kxnnNnrrnNnnNk..',
      'aasnNnrrnNNsSk..',
      'kAksnnnnnNNsSk..',
      '.k.krrNNrrrrk...',
      '...kNNkkNNNk....',
      '..kxNk.kxNNk....',
      '...kk...kkk.....',
    ],
  },
  '呪いの鎧': {
    pal: { k: '#0d0b10', a: '#5a5868', A: '#3a3846', S: '#24222c', x: '#7a7888', e: '#b060ff', p: '#6a3a9a', P: '#3a1a5a', r: '#5a1a1a', s: '#8a8a98' },
    rows: [
      '....kpkk........',
      '...kpkkpk...k...',
      '...kxaaaAk.kpk..',
      '..kxaaaaAAk.k...',
      '..kaSeSSeAk.....',
      '..kaSSSSSAk.....',
      '.kkAaaaaAAkk....',
      'kxxaAAAAAAxxk...',
      'xaaxaaPaaAxAAk..',
      'xaAxaPePaAxAAk..',
      'AAAAaaPaaAAAAk..',
      'ksAkAAAAAAkAsk..',
      'kskkarrrrAkksk..',
      'kskkAAkkAAkksk..',
      'kskxAAkkxAAksk..',
      '.k.kkk..kkk.k...',
    ],
  },
  '夢魔': {
    pal: { k: '#0d0b10', s: '#8a7a8e', S: '#5a4a60', h: '#2a1a2e', H: '#1a101e', e: '#f0e040', w: '#4a2a4a', W: '#2e1a30', r: '#7a2a4a', v: '#6a4a6e', V: '#4a3050' },
    rows: [
      '........k.......',
      '..k.k..kwk....k.',
      '.khkhk.kwwk..kwk',
      '.khhhhkkwWwkkwWk',
      'khhssShkwWWwwWWk',
      'khesesHhwWWWWWWk',
      'khssssHhwWWWWWk.',
      'khSrrSHhHwWWWk..',
      '.khsSSHhHhWWk...',
      '.khvvvvHhHhk....',
      'kskvvrvvHhHk....',
      'ksskvvvvhHk.....',
      '.kkkvvvvvhk.....',
      '...kvVvvvvvk....',
      '....kvkvkvvk....',
      '.....k.k.kk.....',
    ],
  },
  '魔獣': {
    pal: { k: '#0d0b10', b: '#4a2a3a', B: '#2e1824', l: '#6a3e50', h: '#b8ac94', H: '#7a705e', e: '#ff3020', w: '#e8e0c8', m: '#1a0a10', c: '#d8d0c0' },
    rows: [
      '..k.............',
      '.khk.k..........',
      'khHkkhk.........',
      'khHkhHk...k.k.k.',
      '.khhHk...klklklk',
      '.klbblkkklblblbk',
      'klbebbbllbbbbbbB',
      'lbbbbbbbbbbbbbBB',
      'mwmwbbbbbbbbbBBB',
      'kmmmwbbbbbbbbBBk',
      'wmwmbBBbbbbBBBBk',
      'kkkkkBbBbBbBBBBk',
      '...kbbBBkkBbBBbk',
      '..kbbBkk.kBbBkbk',
      '.kccBk..kccBk.k.',
      '..kkk....kkk....',
    ],
  },
  '闇の司祭': recolor(SHAPE_5, { b: '#2e2238', B: '#1a1422', v: '#4a3a5a', f: '#a89aa0', F: '#6e6068', e: '#c050ff', g: '#8a7a40', y: '#7a4ab0', Y: '#c8a0ff', r: '#4a2a6a' }),
  'ガーゴイル': {
    pal: { k: '#0d0b10', s: '#5e626a', S: '#3e424a', l: '#7e828a', t: '#2a2c32', e: '#f0d040', w: '#d8d0c0', h: '#8a8476' },
    rows: [
      '..........k.....',
      '...k.k...klk..k.',
      '..khkhk.klslkklk',
      '..khhhkklssSllsk',
      '.ksssslklsSSsSSk',
      'ksesssSklsSSSSSk',
      'kwsswsSksSSSSSSk',
      '.ksssSSlsSSSSSk.',
      '.klsSSsssSSSSk..',
      'klskSssssSSkk...',
      'kwklSsssSSSk....',
      '.kkssSsSSSSSk...',
      '.kssSksSSSSSk...',
      '.kwwSkssSSSStk..',
      '..kkkwwSSkkttk..',
      '.....kkkk..kk...',
    ],
  },
  '魔王の近衛騎士': {
    pal: { k: '#0d0b10', n: '#3a3444', N: '#24202c', x: '#5e566c', g: '#a8883a', e: '#ff3020', r: '#6a1a22', R: '#420e14', a: '#a8b0bc', A: '#6a7280', w: '#4a3a30' },
    rows: [
      '..kak...............',
      '.kaAak..kk..........',
      '.kaAak.kggkk........',
      '.kaAakkgxnnNk.......',
      '..kwk.kxnnnnNk......',
      '..kwk.knNeNeNk......',
      '..kwk.knNNNNNk......',
      '..kwkkkgNNNNgkk.....',
      '.kxxgxxxnnnnxxxkk...',
      'kxnnngnnnnnnnnnnrk..',
      'kxnggggnrrnNNnnrrk..',
      'knngNgNnrrnNNNnrRk..',
      'kxnggggnnnnNNNNrRk..',
      'knngNgNnwwnNNNnrRk..',
      'knnggggnnnnNNNNrRk..',
      'kNnnngnnnnkNNNNRRk..',
      '.kNNNwNNNkkNNNRRk...',
      '..kkxwkNk.kxNNkk....',
      '..kxNNkk.kxNNNk.....',
      '...kkk....kkkk......',
    ],
  },
  '大魔導師': {
    pal: { k: '#0d0b10', f: '#a89a98', F: '#6e6068', e: '#ff3020', b: '#3a1a40', B: '#24102a', v: '#5a2a64', g: '#a8883a', G: '#6e5824', t: '#c8c0a8', T: '#8a8270', p: '#a050e0', P: '#e0b0ff', s: '#3a2a20' },
    rows: [
      '....kpk.....kk......',
      '...kpPpk...kttk.....',
      '....kpk...ktTTtk....',
      '..kk.k..kktkTktk....',
      '.kvvk..kvvktTTtk....',
      '.kvbvkkvbvkkTTk.....',
      '.kvbbbbbbvkksk..k...',
      '.kvbBffffBkksk.kpk..',
      '.kvbfefeFBkkskkpPpk.',
      '.kvbfffffBkksk.kpk..',
      '.kgvbFttFBgksk..k...',
      'kgvvbbttbbBgsk......',
      'kvvbbbgtbbBfsk......',
      'kvbbbbgbbbBBsk......',
      'kvbbbbgbbbbBsk......',
      'vbbbbbgbbbbBBsk.....',
      'vbbbbbgbbbbbBsk.....',
      'BGBGBBgBBGBGBsk.....',
      'kpkkkkkkkpkkkk......',
      '.k.......k..........',
    ],
  },
  '魔王': {
    pal: { k: '#0d0b10', s: '#5a2a3a', S: '#3a1a28', x: '#7a3a4e', h: '#b8ac94', H: '#7a705e', e: '#ff3020', E: '#ffd040', w: '#e8e0c8', a: '#3a3444', A: '#24202c', g: '#9a7a30', c: '#4a1a22', C: '#2a0e14', p: '#8a4ab0', P: '#d0a0ff' },
    rows: [
      '..k..........................k..',
      '.khk........................khk.',
      '.khhk......................khhk.',
      '.kHhk......................khHk.',
      '..kHhk.....k...kk...k.....khHk..',
      '..kHhhk...kgk.kggk.kgk...khhHk..',
      '...kHhhkkkggkkggggkkggkkkhhHk...',
      '....kHhhhkggggggggggggkhhhHk....',
      '.....kHHhxssssssssssssxhHHk.....',
      '......kksxssssssssssssxskk......',
      '......ksxssEesssssseEssxsk......',
      '.k....kssssSSssssssSSssssk....k.',
      'khk..k.kSssskwkwwkwksssSk.k..khk',
      'khHkkhkkSSsskkkkkkkkssSSkkhkkHhk',
      'kaHkhHkkkSSSSSSSSSSSSSSkkkHhkHak',
      '.kaaaaaaakgAAAAAAAAAAgkaaaaaaak.',
      'kaaxxaaaaagAAaAAAAaAAgaaaaaxxaak',
      'kaxaaaaaAAgAaeaAAaeaAgAAaaaaaxak',
      'kAaaaaaAAcgAAaaAAaaAAgcAAaaaaaAk',
      '.kAAAAAAccgAAAAAAAAAAgccAAAAAAk.',
      '.ksSccccccgAaaAAAAaaAgccccccSsk.',
      'kksScccccCgAaAAAAAAaAgCcccccSskk',
      'PksSccccCCgAAAAaaAAAAgCCccccSskP',
      'pwsSwcccCCgaaAAAAAAaagCCcccwSswp',
      'kwkwkccCCCgAAAAAAAAAAgCCCcckwkwk',
      'kpkkccCCCCgAAAAAAAAAAgCCCCcckkpk',
      '.k.kccCCCCAAaAAAAAAaAACCCCcck.k.',
      '...kcCCCCAAaAAAAAAAAaAACCCCck...',
      '..kccCCCCAAAAAAAAAAAAAACCCCcck..',
      '..kcCCCCAAAAkAAAAAAkAAAACCCCck..',
      '.kccCCCCAAAk.kkkkkk.kAAACCCCcck.',
      '..kkkkkkkkk..........kkkkkkkkk..',
    ],
  },
  '影の暗殺者': {
    pal: { k: '#0d0b10', d: '#1e1a26', D: '#121018', x: '#2e2838', e: '#ff3030', a: '#d0d8e4', A: '#8a93a3', r: '#4a1a2a', R: '#2e101a' },
    rows: [
      '......kkk.......',
      '.....kxxxk......',
      '....kxddDDk.....',
      '...kxeedDDkkk...',
      '...kdddDDDkrrk..',
      '..k.kDdDDrrRkrk.',
      '.kakddddDDDkkRk.',
      'kaAkdddddDDDkk..',
      'aAkdddDdddDDk...',
      'kkddkddDddDDkk..',
      '..kkkdddDDDDkak.',
      '...kdDDkdDDDaAk.',
      '..kdDDk.kdDaAk..',
      '..kdDk...kdDk...',
      '.kDDk...kDDk....',
      '..kk.....kk.....',
    ],
  },
  '骨の竜騎兵': {
    pal: { k: '#0d0b10', h: '#c8c0a8', H: '#8a8270', e: '#e03030', r: '#6a5a40', R: '#3e3426', l: '#a8b0bc', s: '#4a4038', S: '#2e2822', x: '#7a2a2a', w: '#e8e0c8' },
    rows: [
      '.........khk....',
      '....kkkkkhHk....',
      '..kkhhhhhhHk....',
      '.khhhheHhHk.k...',
      'khwhwhhhhHkkxk..',
      '.kkkkkhHHkkxxk..',
      'kkkkrrrRRrxxkkkk',
      'llllsrrrRRllllll',
      'kkksSsrRrRRkkkkk',
      '..ksxSrrRRRhk...',
      '..ksSsrRRRRk....',
      '..ksSskhHkHk....',
      '...kskkhHkhHk...',
      '....k.kRRkkRRk..',
      '.....kRRRkkRRRk.',
      '......kkk..kkk..',
    ],
  },
  '血の祭壇': {
    pal: { k: '#0d0b10', s: '#5a5058', S: '#3a3238', l: '#7a7078', b: '#8a1a1a', B: '#5a0e10', r: '#c02020', e: '#f0d040', E: '#c89020', d: '#1a0a0a', c: '#d8d0b8', f: '#f0a030' },
    rows: [
      '..k.........k...',
      '.kfk.k..k..kfk..',
      '.kckkbkkbkkkck..',
      '.kckbbrbrbbkckk.',
      'klllllllllllllSk',
      'ksbsssbsssbsssSk',
      '.ksbsrrrrssbsSk.',
      '.ksbrdeeedrsSSk.',
      '.kssreEdEersSSk.',
      '.ksbrdeeedrsbSk.',
      '.kssbrrrrrssbSk.',
      '.ksbskssksbsSSk.',
      '.kssssssssssSSk.',
      'klllllllllllSSSk',
      'kSSSSSSSSSSSSSSk',
      '.kbkkBkkkkBkkbk.',
    ],
  },
  '堕ちた聖職者': {
    pal: { k: '#0d0b10', g: '#c8a040', G: '#7a6028', w: '#c8c4b8', W: '#8a867c', d: '#1e1a22', D: '#2e2834', f: '#a89a90', F: '#6e625c', e: '#ff3030', t: '#3a1a2a', p: '#c050ff', r: '#7a1a22' },
    rows: [
      '...kggkggkk.....',
      '..kGkk.kkkgk....',
      '...kggkggGk.....',
      '....kffffk......',
      '...kfefeFk......',
      '...kffffFk......',
      '....kFrFkkk.....',
      '...kwwrwwddk....',
      '..kwwDrwddDdk...',
      '.ktttwrdwdDdk...',
      '.ktptwrdwDDdk...',
      '.ktttfrwdwDDk...',
      '..kkwWrdwdDDk...',
      '...kwWWddDDdk...',
      '..kwWkdDkwDDdk..',
      '...kk.kk.kkkk...',
    ],
  },
};

/** 絵が見つからないときの影 */
export const UNKNOWN_SPRITE: Sprite = {
  pal: { k: '#0d0b10', s: '#3a3644', S: '#26232e', q: '#8a8496' },
  rows: [
    '......kkkk......',
    '.....kssssk.....',
    '....kssssSSk....',
    '....ksqqqsSk....',
    '....ksssqsSk....',
    '.....ksqsSk.....',
    '....kkSsSSkk....',
    '...kssssqsSSk...',
    '..kssssssssSSk..',
    '..kssssqsssSSk..',
    '..ksSkssssSkSk..',
    '...kkkssSSSkk...',
    '.....ksSkSSk....',
    '.....ksSkSSk....',
    '.....kSSkSSk....',
    '......kk.kk.....',
  ],
};
