// Enemies: face LEFT. Normal 16x16, elites 20x20, bosses 24..32.
const STEEL = { a: '#8a93a3', A: '#5a6170', S: '#3a3f4c' };

export const ENEMIES = {
  // ---------------- floor 1: dusk grassland ----------------
  スライム: {
    pal: { g: '#5a6a3a', G: '#3a4626', l: '#7a8a50', e: '#e0c840', E: '#d03030', w: '#d8d0b8', b: '#c8bfa8', r: '#5a2a2a' },
    rows: [
      '................',
      '................',
      '................',
      '.........b......',
      '........bb......',
      '......lgbgl.....',
      '....llgggggll...',
      '...lgeggggEgggl.',
      '..lgggggggggggG.',
      '.lgEggggglgggGG.',
      '.gwrwrwgggggggG.',
      '.grrrrrggggGgGG.',
      '.ggwgwgggGGGGGG.',
      '..GgGGgGGGGGGGG.',
      '..G.G..GG..G.GG.',
      '................',
    ],
  },
  野ウサギ: {
    pal: { b: '#6a5040', B: '#46342a', l: '#8a7058', e: '#e03030', w: '#d8d0c0', p: '#7a4a48' },
    rows: [
      '................',
      '.......bb.bb....',
      '.......lp.lp....',
      '.......lp.lp....',
      '.......lb.lb....',
      '.....lbbbbbb....',
      '....lbbbbbbb....',
      '...lbebbbbbbb...',
      '..lbbbbbbbbbbbb.',
      '..bbbbbbbbbbbbBl',
      '..Bwbbbblbbbbbbl',
      '...BbbbbbbbbBBB.',
      '....BbbbbbbBBBB.',
      '....BB.BBB..BBB.',
      '...BB..BB...BB..',
      '................',
    ],
  },
  大ガラス: {
    pal: { c: '#2e2e3a', C: '#1e1e28', l: '#4a4a5e', y: '#6a6050', e: '#e03030' },
    rows: [
      '................',
      '..........lll...',
      '.........lcCCl..',
      '........lcCCCC..',
      '.......lcCCCCC..',
      '...cc.lcCCCCc...',
      '..ceccccCCCc....',
      'yyccccccccccc...',
      '.yycccccCCCCCcc.',
      '...ccccCCCCCCCcc',
      '....cccCCCCC.cc.',
      '.....cc..cCc....',
      '......y..y......',
      '.....yy.yy......',
      '................',
      '................',
    ],
  },
  毒キノコ: {
    pal: { p: '#6a3a5a', P: '#3e2238', s: '#a89878', w: '#a8a090', W: '#6e6858', e: '#e0d040', r: '#4a2a2a', t: '#d8d0b8', g: '#8aa040' },
    rows: [
      '................',
      '...g.......g....',
      '.....pppppp.....',
      '...pppsppppp..g.',
      '..ppppppppsppp..',
      '.ppsppppppppppP.',
      '.pppppppsppppPP.',
      '.PPppppppppPPPP.',
      '..PPPPPPPPPPPP..',
      '...wewweWWWW....',
      '...wwwwwwWWW..g.',
      'g..rtrtrwWWW....',
      '...rrrrrwWWW....',
      '...wwwwwwwWW....',
      '..WWWWwwWWWWW...',
      '................',
    ],
  },
  草原オオカミ: {
    outline: false,
    pal: { e: '#e03030', w: '#e8e2d0', g: '#4a4a58', G: '#2e2e3a', l: '#6a6a7c' },
    rows: [
      '................',
      '..k..k..........',
      '.klk.klk........',
      '.kggkggk........',
      'kgggggggk.......',
      'kgegggggGk......',
      'kgggggggggkkkkk.',
      'kwkwgggggggggGGk',
      '.kkkgggggggggGk.',
      '...kGgggglggGGk.',
      '...kGGggGGGggGk.',
      '...kGkGGk.kGGGk.',
      '...kGk.kGk.kGkk.',
      '...kk..kk..kk...',
      '................',
      '................',
    ],
  },
  雪狼: { base: '草原オオカミ', pal: { g: '#a8aebc', G: '#6a7084', l: '#d0d4e0', e: '#e8c030' } },
  野盗: {
    pal: { f: '#c8a080', d: '#1a1418', h: '#5a4a38', H: '#3a3024', r: '#6a2a2a', L: '#5a4030', b: '#2a1e16', o: '#b08a3a', a: '#a8b0bc', A: '#6a7280', S: '#2a2224', g: '#8a7a3a', G: '#5a4e26' },
    rows: [
      '................',
      '.....hhhhh......',
      '....hhhhhhH.....',
      '....hffffhH.....',
      '....fdffhhH.....',
      '....rrrrrhH.....',
      '.....rrrrH......',
      '...LLLrLLLL.....',
      '..LLLLLLLLLL....',
      'aAfLLLLLLLLLf...',
      '....LbbobLL.gG..',
      '....HHHHHH..GGG.',
      '....HH..HH..GG..',
      '....HH..HH......',
      '...SS..SS.......',
      '................',
    ],
  },
  森の大熊: {
    size: 20,
    pal: { b: '#4a3a30', B: '#2e241e', l: '#6a5444', e: '#e03030', w: '#d8d0c0', r: '#6a2222', s: '#8a6a5a', n: '#1a1418' },
    rows: [
      '....................',
      '....................',
      '....................',
      '.........llll.......',
      '.......llbbbbll.....',
      '...ll.lbbbbbbbbll...',
      '..lbblbbbbbbbbbbbl..',
      '..lbbbbbbbbbbbbbbbB.',
      '.lbebbbbbbsbbbbbbbB.',
      '.lbbbbbbbbbsbbbbbbB.',
      'nbbbbbbbbbbbsbbbbBB.',
      '.rwrwbbbbbbbbbbbbBB.',
      '..rrrBbbbbbbbbbbBBB.',
      '...BbbbBbbbbbbbBBBB.',
      '...bbbBB.BbbbbBBbbB.',
      '...bbbB...BbbB.BbbB.',
      '..bbbbB...BbbB.BbbB.',
      '..wwwBB..wwbB.wwBB..',
      '....................',
      '....................',
    ],
  },
  野盗の用心棒: {
    size: 20,
    pal: { f: '#b08868', F: '#7a5a44', d: '#1a1418', e: '#e0c040', s: '#d8c0a8', L: '#4a3424', M: '#2e2018', u: '#6a5a48', w: '#5a4030', W: '#3a2a1e', a: '#8a93a3', A: '#5a6170', r: '#6a2a2a', b: '#2a1e16', o: '#b08a3a' },
    rows: [
      '....................',
      '............a.a.....',
      '......ffff..wWwa....',
      '.....ffffff.awWw....',
      '.....fdffsF.wWwa....',
      '....ffffsfF.awW.....',
      '.....rrfFFF..W......',
      '......fFFF...W......',
      '...uuuLLLLuuuW......',
      '..uuLLLLLLLLufW.....',
      '.ffLLMLLLLLLLffF....',
      '.ffLLLMLLLLLLFF.....',
      '.ffuLLLMLLLLL.......',
      '..F.bbbobbbbb.......',
      '....MMMMMMMMM.......',
      '....MMMM.MMMM.......',
      '....MMM...MMM.......',
      '...WWWW..WWWW.......',
      '....................',
      '....................',
    ],
  },
  '草原の主（大角獣）': {
    size: 24,
    pal: { b: '#5a4632', B: '#3a2c20', m: '#3e2e20', M: '#261c12', l: '#8a7252', h: '#c8bca0', H: '#8a806a', e: '#f0c030', E: '#e03030', n: '#1a1418', w: '#d8d0c0', s: '#9a7a5a', r: '#6a2a20' },
    rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '..h.....................',
      '.hH.......H....mmmm.....',
      '.hH......HH..mmmmmmmm...',
      '.hH.....HH..mmmmmmmmmmb.',
      '..hhH...H.mmmmmmmmmmmbb.',
      '...hhH.mmmmmmmmmMmmmbbB.',
      '....hhmmmmmmmmmMbbbbbbB.',
      '...llmmmmmmmmMMbbbbbbbB.',
      '..lbbeEmmmmmMbbbbbsbbbB.',
      '.lbbbmmmmmmMbbbbbbsbbbB.',
      '.bbbbbmmmmMbbbbbbbbsbBB.',
      'nbbbbbbmmMbbbbbbbbbbBBB.',
      'nbbbbbbbMbbbbbbbbbbbBBB.',
      '.rwbbbbMMbbbbbbbbbbBBB..',
      '..BbbbMMBBbbbBBBBBBBBB..',
      '...BB.MbB.BbbB..BbbBbB..',
      '......bbB.BbbB..BbB.bbB.',
      '......bbB..bbB..BbB.bbB.',
      '.....HHHB.HHHB.HHHB.HHB.',
      '........................',
    ],
  },
  腐肉の蠅群: {
    pal: { b: '#4e5a26', B: '#2c3416', m: '#8a9a3a', w: '#8a9496', W: '#5a6466', e: '#e03030', o: '#5a3a28', O: '#3a2418', r: '#7a3a32', c: '#c8bca0' },
    rows: [
      '................',
      '.ww.............',
      'wWw......w......',
      'ebmb....wWw.ww..',
      '.bBB...wwwWwWww.',
      '.B.B..mbbwWwbw..',
      '.....ebmbbbbbB..',
      '.....bbbBbBbBBB.',
      '......BbBbBbBB..',
      '..ww...B.B.B....',
      '.wWw..........w.',
      'ebmbB........wWw',
      '.BbB..oro...ebmb',
      '....ooOrrOo..BbB',
      '...orcrrcrrO....',
      '..OOOOOOOOOOO...',
    ],
  },
  墓荒らし: {
    pal: { g: '#5e5648', c: '#4a443a', C: '#2c2822', d: '#141016', e: '#e0c040', f: '#8a7a68', a: '#9a6a3a', A: '#5a3a22', h: '#5a4030', l: '#f0c050', L: '#3a3030', n: '#1e1a18' },
    rows: [
      '................',
      '..aaa...........',
      '.aAAAa..........',
      'aA...A..........',
      'a....h..cccc....',
      'a....h.cgggcC...',
      '.a...hccdddcCC..',
      '.....hcdedecCCC.',
      '....ffcdddcCCCC.',
      '....ffccccCcCCC.',
      '.....hcccCcCCCC.',
      '.....hcCcCCCCC..',
      '.....h.CCcCCC.L.',
      '......CC..CC.LlL',
      '.....nn..nn..LlL',
      '..............L.',
    ],
  },
  首吊りカカシ: {
    pal: { p: '#4a3a2a', P: '#2e241a', s: '#8a7a58', S: '#5e523a', e: '#f0c030', d: '#1a1418', r: '#a08a5a', c: '#4a3a4a', C: '#2e2430', y: '#a89848', h: '#3a3028', H: '#241e18', f: '#1e1e28' },
    rows: [
      '.......hh.......',
      '......hhhH......',
      '....hhhhhhhH....',
      '......sssS......',
      '......eseS......',
      '......dsdS......',
      '.......rrr.r....',
      'y.cccccrcccr.cy.',
      'yppcCccccCcrpPPy',
      '..f.cccCcccr.f..',
      '....cCcCcCcC....',
      '.....yc.yc.y....',
      '.......pP.......',
      '.......pP.......',
      '......PpPP......',
      '................',
    ],
  },
  牙イノシシ: {
    pal: { x: '#6a4a40', b: '#3e3428', B: '#241e18', l: '#5a4c3a', m: '#16120e', t: '#e0d8c0', T: '#a89e86', e: '#ff3020', n: '#7a5a50', h: '#1a1418' },
    rows: [
      '................',
      '................',
      '........m.m.m...',
      '......mmmmmmmmm.',
      '....lmmbmbmbmmmm',
      '...lbbbbbbxbbbmB',
      '..lbebbbbbbxbbbB',
      't.lbbbbbbbbbbbBB',
      'tnbbbbbbbbbbbBBB',
      'tnnTbbbbbbbbBBB.',
      '.ttTBbBBbbbBBBB.',
      '....BbB.BbbBBB..',
      '....BB...BB.BB..',
      '...hh...hh..hh..',
      '................',
      '................',
    ],
  },
  // ---------------- floor 2: icy ----------------
  雪ウサギ: { base: '野ウサギ', pal: { b: '#c4c8d2', B: '#8a90a2', l: '#e4e8f0', p: '#b8a0b0', e: '#e03030' } },
  氷の精: {
    pal: { i: '#9ac8e0', I: '#5a88a8', j: '#3a5a7a', w: '#e0f0ff', e: '#60e0ff', d: '#1a2a40', s: '#c8e8ff' },
    rows: [
      '................',
      '........w.......',
      '.......wi.......',
      '...s..wiiI......',
      '......wiiI...s..',
      '.....wiiiII.....',
      '....wjiiijII....',
      '...wiieiieIIj...',
      '...wiiiiiiIIj...',
      '....wdwdwdIj....',
      '.s...iiiiIj.....',
      '.....IiiIIj..s..',
      '......IIIj......',
      '.......Ij.......',
      '....s..j........',
      '................',
    ],
  },
  凍った亡者: {
    pal: { f: '#7a8a98', F: '#52606e', G: '#384450', e: '#60d0ff', r: '#3e3a4a', R: '#28252f', i: '#c8e8ff', I: '#8ab8d8', t: '#c8c0a8' },
    rows: [
      '................',
      '.....i...i......',
      '.....ffffiI.....',
      '....fFffffF.....',
      '....eFffffF.....',
      '....fffffFF.....',
      '....ttGfFFF.....',
      '...rrGGFFFrr....',
      'ff.rrrrrrrrrr...',
      '.Ffffrrrrrrrrr..',
      '...ffRrrrrrRr...',
      '....RrrRrrRRr...',
      '....RrRR.RrRR...',
      '....fF...fF.....',
      '...IIii.iIII....',
      '................',
    ],
  },
  氷柱コウモリ: {
    pal: { b: '#4a5266', B: '#2e3444', l: '#6a7488', e: '#e03030', w: '#e8e8f0', i: '#a8d8f0', I: '#6aa0c8' },
    rows: [
      '................',
      '................',
      '.....b....b.....',
      'l...bbb..bbb...l',
      'll..bebbbbbb..ll',
      'lbl.bbwbbbbb.lbl',
      'lbbbbbbbbbbbbbbl',
      'BbbbbbbbbbbbbbbB',
      'BBbBbbbbbbbbBbBB',
      'B.BBBBbbbbBBBB.B',
      '..i.B.IBBI.B.i..',
      '..I...i..i...I..',
      '......I..I......',
      '................',
      '................',
      '................',
    ],
  },
  雪原の小鬼: {
    pal: { g: '#6a7a5a', G: '#46523a', e: '#e0c040', w: '#d8d0c0', u: '#c8c4bc', U: '#8a8680', c: '#5a4030', C: '#3a2a1e', s: '#6a7280', S: '#454b58', o: '#a08a5a' },
    rows: [
      '................',
      '.....uuuu.......',
      '....uuuuuU......',
      '...uggggguU.....',
      '..geggggGuU..c..',
      '..gggggGGuU.cC..',
      '...wgwgGGU..cC..',
      '..ssssuUUU.gC...',
      '.sSoSsUUuUgG....',
      '.sSoSSsUUUU.....',
      '.sSoSsUUUU......',
      '.ssSsCCCCC......',
      '..ss.GG.GG......',
      '.....GG.GG......',
      '....CC..CC......',
      '................',
    ],
  },
  雪男: {
    size: 20,
    pal: { w: '#c8ccd8', W: '#8a90a4', V: '#5e6478', f: '#5a7088', F: '#3a4a60', e: '#e03030', t: '#e8e4d8', r: '#4a2030', c: '#2a3040' },
    rows: [
      '....................',
      '.......wwwwww.......',
      '......wwwwwwwW......',
      '.....wwffffwwWW.....',
      '....wwfefffwwWWW....',
      '....wfffffFwwWWWW...',
      '..wwwrtrtFFwwWWWWW..',
      '.wwwwrrrrFwwwWWWWWW.',
      '.wwwwwtwtwwwwWWWWWW.',
      'wwWwwwwwwwwwwWWWWWWV',
      'wWWwwwwwwwwwWWWWWWVV',
      'wWW.wwwwwwwWWWWW.WVV',
      'wWW.wwwwwwWWWWWW.WVV',
      'fcf.WwwwwwWWWWWV.VVV',
      'fFf.WWwwwWWWWWVV.FcF',
      '....WWWWW.WWWWVV....',
      '....WWWW...WWWVV....',
      '...WWWWW...WWWVVV...',
      '...ffff....ffFF.....',
      '....................',
    ],
  },
  氷の魔術師: {
    size: 20,
    pal: { f: '#a8b0c0', F: '#6e7888', d: '#1a1418', e: '#80e0ff', b: '#2e4a6a', B: '#1c2e46', v: '#4a6e94', c: '#c8e8ff', C: '#80b8e0', g: '#a8b8c8', s: '#4a5a6a' },
    rows: [
      '........c...........',
      '.......cCc....c.....',
      '......cbbbc..cCc....',
      '.....cbbbbbc..C.....',
      '.....bbbbbbbB.c.....',
      '....vbBffffBB.s.....',
      '....vbfeffeFB.s.....',
      '....vbfffffFB.s.....',
      '....vbBFggFBB.s.....',
      '...vvbbbggbbBfs.....',
      '..vvbbbbggbbBBs.....',
      '..vbbbbcggbbbBs.....',
      '..vbbbbCbbbbbBs.....',
      '.vbbbbbcbbbbbBs.....',
      '.vbbbbbCbbbbbbBs....',
      'vbbbbbbcbbbbbbBBs...',
      'vbbbbbbCbbbbbbBBBs..',
      'BBcBBBBcBBBcBBBBBB..',
      '.c...C....c...C.....',
      '....................',
    ],
  },
  氷の女王: {
    size: 24,
    mirror: true,
    pal: { c: '#c8e8ff', C: '#80b8e0', j: '#4a7aa8', f: '#c0c8d4', F: '#8a94a8', e: '#80f0ff', h: '#a8c0d8', H: '#6a84a0', g: '#2a4a6e', G: '#1a3050', v: '#4a6e94', r: '#3a2a4a', w: '#e8f4ff' },
    rows: [
      '...........c',
      '.....c....cC',
      '.....cC..cCC',
      '......cCcCCc',
      '......cjjjjj',
      '.....hhhhhhh',
      '....hhHfffff',
      '....hHffeeff',
      '...hhHfffff.',
      '...hHHFffFFF',
      '..hhH.FFrrrF',
      '..hHH.gvFFFF',
      '..hH.gvvgggg',
      '.hhHgvwgggGg',
      '.hH.gvgggggG',
      '.hHCgvvggGgg',
      '..C.gvggggGG',
      '...gvvgggggG',
      '...gvggggGgG',
      '..gvvggggGGG',
      '..gvgggggGGg',
      '.gvvggggGGGG',
      '.cCcCcCcCcCc',
      '............',
    ],
  },
  霜の亡霊: {
    pal: { g: '#a8c0d0', G: '#6a8498', l: '#d8e8f0', d: '#141822', e: '#80f0ff', i: '#e8f8ff', w: '#5a7088' },
    rows: [
      '................',
      '......llll......',
      '.....lgggglG....',
      '....lgggggggG...',
      '....gddggddgG...',
      '....gdeggdegG...',
      '....ggggggggGG..',
      '...lggdddggGGG..',
      '..lggdddddgGGGw.',
      '.i.gggdddgGGGGww',
      'igl.ggggGGGGGw..',
      '.i..gGgGGGGwww..',
      '....GgGGwGwww...',
      '......Gw.www....',
      '..........ww....',
      '................',
    ],
  },
  氷蜘蛛: {
    pal: { b: '#3a4a5e', B: '#222c3a', l: '#5a7088', i: '#a8d8f0', I: '#6aa0c8', j: '#e8f8ff', e: '#60f0ff' },
    rows: [
      '................',
      '................',
      '..j.........j...',
      '..ii.......iI...',
      '..I.i.lll.i.I...',
      '.i...Iblbbbl.I..',
      '.I..IbbbbbbbbI..',
      'i..eebbbbbbbbbI.',
      'I.ebebbbbblbbbbI',
      '..BbbbbbbbbbbbB.',
      '.IIBBbbbbbbbbBBI',
      'I...IBBBBBBBB..I',
      'I..I..I...I...I.',
      '..I..I....I..I..',
      '.j..j......j..j.',
      '................',
    ],
  },
  凍てつく骸骨弓兵: {
    pal: { h: '#c8c4b4', H: '#8a8676', i: '#d8f0ff', I: '#8ac0e0', c: '#3a5a7a', C: '#243a52', e: '#60e0ff', d: '#141418', w: '#5a4a3a', W: '#3a2e22', s: '#a8a090', a: '#8a93a3' },
    rows: [
      '...w..iii.......',
      '..wW.hhhhi......',
      '..w.hhhhhhH.....',
      '.w.sdedhdhH.....',
      '.w.s.hhhhH......',
      '.w.s.hdhdcc.....',
      'w..sahhccccC....',
      'wa.ahhhHhcCCc...',
      'w..s.chHhCcCC...',
      '.w.s.cHhHCcCc...',
      '.w.s..CcCcCcC...',
      '.w.s...hcHC.....',
      '..wW...h..H.....',
      '...w...h..H.....',
      '......iIh.iIH...',
      '................',
    ],
  },
  吹雪の鷲: {
    pal: { w: '#d8dce4', W: '#9aa2b0', g: '#5e6678', b: '#d8b040', e: '#e8c030', i: '#a8e0ff', I: '#6ab0e0', t: '#3a3a44' },
    rows: [
      '.i.............i',
      '.Ii...........iI',
      '..Wi.........iW.',
      '..WWi.......iWW.',
      '...WWw.....wWWg.',
      '...gWWw...wWWg..',
      '....gWWwwwWWg...',
      '.....gWwwwWg....',
      '......wwwWWg....',
      '....wwwwgWW.....',
      '...wwewwWg......',
      '..bbwwwWWg......',
      '..b.wwWWtg......',
      '.......t.t......',
      '................',
      '................',
    ],
  },
  // ---------------- floor 3: volcano ----------------
  火トカゲ: {
    pal: { r: '#8a3a20', R: '#5a2414', l: '#b05a2a', y: '#e8a030', Y: '#f0e070', e: '#f0e040', w: '#d8d0c0' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '.............Y..',
      '.............yY.',
      '..lll.......yyy.',
      '.leRrl.l.l.lyy..',
      'lrrrrrrlrlrrrry.',
      'wkwrrrrrrrrrrRR.',
      '.RRRRrrrrrrrRR..',
      '...RRRRRRRRRR...',
      '...R.RR...RRR...',
      '..RR..RR..R.RR..',
      '................',
      '................',
    ],
  },
  溶岩スライム: { base: 'スライム', pal: { g: '#a8401a', G: '#5a1e10', l: '#e8862e', e: '#fff080', E: '#ffd040', w: '#e8d0a0', b: '#2e2626', r: '#2a1010' } },
  火の鳥: { base: '大ガラス', pal: { c: '#c04a1a', C: '#7a2a10', l: '#f0a030', y: '#f0d060', e: '#fff080' } },
  岩ゴーレム: {
    pal: { s: '#6a6258', S: '#4a443c', t: '#2e2a26', l: '#8a8276', e: '#e0c040', m: '#5a6a3a' },
    rows: [
      '................',
      '....llls........',
      '...lsssssS......',
      '...seSssSS......',
      '...sssssSS......',
      '..llsSSSSllls...',
      '.lssstsssssssS..',
      '.ssSsssstssSSS..',
      '.sSS.sstsssSSSS.',
      '.sSS.ssssssS.SS.',
      'lssS.SSsSSSS.sSS',
      'sSSS.ss..sSS.SSS',
      '.....ss..sSS....',
      '....lss..sSSS...',
      '....SSS..SSSS...',
      '................',
    ],
  },
  火山コウモリ: { base: '氷柱コウモリ', pal: { b: '#5a2a26', B: '#36181a', l: '#8a3a2a', e: '#f0e040', i: '#f0a030', I: '#c04a1a' } },
  炎の魔導師: {
    pal: { f: '#b89880', F: '#7a6050', d: '#1a1418', e: '#f0e040', b: '#6a2418', B: '#401410', v: '#8a3a20', g: '#b0903a', s: '#3a2a20', y: '#f0a030', Y: '#fff080', r: '#c04a1a' },
    rows: [
      '................',
      '.......bb.......',
      '......vbbB......',
      '.....vbbbbB.....',
      '....vbBBBBbB....',
      '...Y.vefeFbB....',
      '..yYy.FfFFBB....',
      '..ryr.vbgbbB....',
      '...fvvbbgbbbB...',
      '...vvbbbgbbbB...',
      '...vbbbbgbbbB...',
      '...vbbbbgbbbBB..',
      '..vbbbbbgbbbbB..',
      '..vbbbbbgbbbbBB.',
      '..BBBBBBBBBBBBB.',
      '................',
    ],
  },
  溶岩ゴーレム: {
    size: 20,
    pal: { s: '#3a2e2a', S: '#241c1a', l: '#5a4a42', y: '#f0a030', Y: '#fff080', r: '#c04a1a', e: '#fff080' },
    rows: [
      '....................',
      '.......lllls........',
      '......lsssssS.......',
      '.....lsYeyssSS......',
      '.....ssyrsrsSS......',
      '...llssssssSSSlls...',
      '..lssssrsssssSSSSS..',
      '.lsssSsyrssSssSSSSS.',
      '.ssSSssrYrsSsSSSSSS.',
      '.ssSS.ssryssS.SSSSS.',
      '.ssSS.sssrssS.SSrSS.',
      'lssrS.ssssrsS.SrySS.',
      'ssryS.SsssyrS.SSrSS.',
      'sryYs.SSSSSSS.SSSSS.',
      'SSSS..ssS..ssS..SS..',
      '.....lssS..ssSS.....',
      '.....sryS..syrS.....',
      '.....ssSS..ssSSS....',
      '....SSSSS..SSSSS....',
      '....................',
    ],
  },
  サラマンダー: {
    size: 20,
    pal: { r: '#9a3a1a', R: '#5e2010', l: '#c8602a', y: '#f0a030', Y: '#fff080', e: '#fff080', w: '#e8e0c8', m: '#3a1008' },
    rows: [
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '.........y..y.......',
      '........yYyyYy.y....',
      '.......yyyyyyyyYy...',
      '...lll.lrrrrrrryy...',
      '..lerrlrrrrrrrrrry..',
      '.lrrrrrrrrrrrrrrrry.',
      'lrrrrrrrlrrrrrrrRRyY',
      'mwmwrrRrrrrrrrrRRRRy',
      '.mmmmRRrRRrrrrRRRR..',
      'wkwk.RRrRRRRRRRRRR..',
      '.....rR.RR...RR.R...',
      '....rr..RR..rR..RR..',
      '...ww..ww..ww...ww..',
      '....................',
    ],
  },
  炎竜: {
    size: 32,
    pal: { p: '#b8783a', P: '#7e4e26', r: '#8a2a1a', R: '#561810', l: '#b04a24', m: '#3a0e08', h: '#c8bca0', H: '#8a806a', e: '#fff060', w: '#e8e0c8', y: '#f0a030', Y: '#fff080', o: '#e06020', b: '#6a3a2a', B: '#3e2018' },
    rows: [
      '................................',
      '................................',
      '......................RR........',
      '.....................RRRRR......',
      '.....................RbbRRRRR...',
      '....................RbbbRbbbRRR.',
      '....................RbbbRbbbbbR.',
      '..........hh.......RbbbbRbbbbbR.',
      '.........hH........RbbbRbbbbbbR.',
      '....lll.hH.......RRbbbbRbbbbRRR.',
      '...lrrrrhr.......RbbbbRbbbbbR...',
      '..lrrerrrrr.....RbbbbRbbbbbR....',
      '.lrrrrrrrrrr....RbbbRbbbbbR.....',
      'lrrrrrrrrrrrr..RbbbbRbbbbR......',
      'mwmwmwrrrrrrrl.RbbbRbbbbR.......',
      '.mmmmoorrrrrrrlRbbbbRbbbR.......',
      'wmwmwRRRrrrrrrrRbbbRRRRR........',
      '.RRRRR..RRrrrrrrrll.............',
      '.........RRrrrrrrrrrll..........',
      '..........RRpprrrrrrrrrl........',
      '..........RppPrrrrrrrrrrl.......',
      '..........RpPprrrrrrrrrrrl......',
      '...........pPprrrrrrrrrrrrl.....',
      '...........RPprrrrrrrrrrrrrl....',
      '...........RRrrrrRRrrrrrrrrRrr..',
      '...........rrRRRRrRRRRrrrrRRrrr.',
      '..........rrrR....RRRrrRR..RRrr.',
      '.........rrrR.....RrrrR.....RRr.',
      '.........rrR......RrrR.......Rr.',
      '........wwRR.....wwRR.......Rr..',
      '...........................RR...',
      '................................',
    ],
  },
  火吹き小鬼: {
    pal: { s: '#2a2426', S: '#18141a', l: '#4a3a38', e: '#ffd040', h: '#8a7a6a', f: '#f0a030', F: '#c04a1a', y: '#fff080', o: '#e8602a', w: '#5a2a26', W: '#3a1a18', t: '#2a2426' },
    rows: [
      '................',
      '......h...h.....',
      '......hh.hh.....',
      '.......ssss..w..',
      '......sesssSww..',
      'y.F..ssssssSwW..',
      'fyfFFossssSwwW..',
      '.fyfFoosssSSwW..',
      '..F...ssSSS.W...',
      '.....lsoSsSS....',
      '....ss.sosSS....',
      '.....l.ssSSS....',
      '......sS..sS..t.',
      '.....SS..SS..tt.',
      '............t...',
      '................',
    ],
  },
  黒曜の蠍: {
    pal: { o: '#2a2430', O: '#16121a', l: '#5a4e6a', L: '#8a7aa0', s: '#ff8a20', S: '#ffd060', e: '#ff6020' },
    rows: [
      '................',
      '......SsS.......',
      '.......ss.......',
      '........oO......',
      '.........oOo....',
      '..........oOO...',
      '.llo.......oO...',
      'lo........loO...',
      'l...o..loooOO...',
      'lo.oOoeoooooooO.',
      '.ooOooooooolooOo',
      '...O.oOoOoOoOO..',
      '....O.O.O.O.O...',
      '................',
      '................',
      '................',
    ],
  },
  溶岩の大蛇: {
    pal: { s: '#3a2420', S: '#22140f', c: '#f08a20', C: '#ffd050', e: '#fff080', f: '#e8d8b8', t: '#c02020', l: '#5a3428' },
    rows: [
      '................',
      '................',
      '...sss..........',
      '..sesSs.........',
      '.tsfsSSs........',
      't.f.sSSs........',
      '....lsSs........',
      '.....sSs........',
      '....lsSS.ss.....',
      '...sscsSsscSs...',
      '..ssSsscSsSsSs..',
      '.lscSsSsscSssSs.',
      '.sSsssccsSsssSS.',
      '..SSsSsSSsSsSS..',
      '...SSSSSSSSSS...',
      '................',
    ],
  },
  燃えさかる骸: {
    pal: { b: '#2e2220', B: '#1a1210', g: '#c04a1a', f: '#f08a20', F: '#c03a10', y: '#ffe070', e: '#fff080', h: '#a89878' },
    rows: [
      '......y.f.......',
      '.....fyFf.y.....',
      '....fFyffFf.....',
      '.....FbbbbF.f...',
      '....fbebbBbFf...',
      '....FbbbbBBf....',
      '.....bhbhBF.....',
      '..hbbbbbgbBBf...',
      '.h.bbgbbbbBBF...',
      '....bbbgbBBbB...',
      '....bBbbbBBf....',
      '....bbB.bBB.....',
      '....bB..bB......',
      '...fbB.FbB......',
      '..FfFfFfFfF.....',
      '................',
    ],
  },
  // ---------------- floor 4: demon castle ----------------
  魔族の兵士: {
    pal: { ...STEEL, s: '#7a3040', S: '#4e1e2a', h: '#b8ac94', e: '#f0d040', n: '#3a3444', N: '#24202c', x: '#5a5266', r: '#6a1a22' },
    rows: [
      '................',
      '...h......h.....',
      '...hh....hh.....',
      '....hnnnnh......',
      '....xnnnnN......',
      '....eSsssN......',
      '....SssSsN......',
      '....NSSSNN......',
      '..xxnnnnnnxx....',
      '.xnnNnrrnNnnN...',
      'aasnNnrrnNNsS...',
      '.A.snnnnnNNsS...',
      '....rrNNrrrr....',
      '....NN..NNN.....',
      '...xN...xNN.....',
      '................',
    ],
  },
  呪いの鎧: {
    pal: { a: '#5a5868', A: '#3a3846', S: '#24222c', x: '#7a7888', e: '#b060ff', p: '#6a3a9a', P: '#3a1a5a', r: '#5a1a1a', s: '#8a8a98' },
    rows: [
      '.....p..........',
      '....p..p........',
      '....xaaaA...p...',
      '...xaaaaAA......',
      '...aSeSSeA......',
      '...aSSSSSA......',
      '...AaaaaAA......',
      '.xxaAAAAAAxx....',
      'xaaxaaPaaAxAA...',
      'xaAxaPePaAxAA...',
      'AAAAaaPaaAAAA...',
      '.sA.AAAAAA.As...',
      '.s..arrrrA..s...',
      '.s..AA..AA..s...',
      '.s.xAA..xAA.s...',
      '................',
    ],
  },
  夢魔: {
    pal: { s: '#8a7a8e', S: '#5a4a60', h: '#2a1a2e', H: '#1a101e', e: '#f0e040', w: '#4a2a4a', W: '#2e1a30', r: '#7a2a4a', v: '#6a4a6e', V: '#4a3050' },
    rows: [
      '................',
      '........w.......',
      '..h.h...ww....w.',
      '..hhhh..wWw..wW.',
      '.hhssSh.wWWwwWW.',
      '.hesesHhwWWWWWW.',
      '.hssssHhwWWWWW..',
      '.hSrrSHhHwWWW...',
      '..hsSSHhHhWW....',
      '..hvvvvHhHh.....',
      '.s.vvrvvHhH.....',
      '.ss.vvvvhH......',
      '....vvvvvh......',
      '....vVvvvvv.....',
      '.....v.v.vv.....',
      '................',
    ],
  },
  魔獣: {
    pal: { b: '#4a2a3a', B: '#2e1824', l: '#6a3e50', h: '#b8ac94', H: '#7a705e', e: '#ff3020', w: '#e8e0c8', m: '#1a0a10', c: '#d8d0c0' },
    rows: [
      '................',
      '..h.............',
      '.hH..h..........',
      '.hH.hH..........',
      '..hhH.....l.l.l.',
      '..lbbl...lblblb.',
      '.lbebbbllbbbbbbB',
      'lbbbbbbbbbbbbbBB',
      'mwmwbbbbbbbbbBBB',
      '.mmmwbbbbbbbbBB.',
      'wmwmbBBbbbbBBBB.',
      '.....BbBbBbBBBB.',
      '....bbBB..BbBBb.',
      '...bbB....BbB.b.',
      '..ccB....ccB....',
      '................',
    ],
  },
  闇の司祭: { base: '炎の魔導師', pal: { b: '#2e2238', B: '#1a1422', v: '#4a3a5a', f: '#a89aa0', F: '#6e6068', e: '#c050ff', g: '#8a7a40', y: '#7a4ab0', Y: '#c8a0ff', r: '#4a2a6a' } },
  ガーゴイル: {
    pal: { s: '#5e626a', S: '#3e424a', l: '#7e828a', t: '#2a2c32', e: '#f0d040', w: '#d8d0c0', h: '#8a8476' },
    rows: [
      '................',
      '..........l.....',
      '...h.h...lsl..l.',
      '...hhh..lssSlls.',
      '..ssssl.lsSSsSS.',
      '.sesssS.lsSSSSS.',
      '.wsswsS.sSSSSSS.',
      '..sssSSlsSSSSS..',
      '..lsSSsssSSSS...',
      '.ls.SssssSS.....',
      '.w.lSsssSSS.....',
      '...ssSsSSSSS....',
      '..ssS.sSSSSS....',
      '..wwS.ssSSSSt...',
      '.....wwSS..tt...',
      '................',
    ],
  },
  魔王の近衛騎士: {
    size: 20,
    pal: { n: '#3a3444', N: '#24202c', x: '#5e566c', g: '#a8883a', G: '#6e5824', e: '#ff3020', r: '#6a1a22', R: '#420e14', a: '#a8b0bc', A: '#6a7280', w: '#4a3a30' },
    rows: [
      '...a................',
      '..aAa...............',
      '..aAa...gg..........',
      '..aAa..gxnnN........',
      '...w...xnnnnN.......',
      '...w...nNeNeN.......',
      '...w...nNNNNN.......',
      '...w...gNNNNg.......',
      '..xxgxxxnnnnxxx.....',
      '.xnnngnnnnnnnnnnr...',
      '.xnggggnrrnNNnnrr...',
      '.nngNgNnrrnNNNnrR...',
      '.xnggggnnnnNNNNrR...',
      '.nngNgNnwwnNNNnrR...',
      '.nnggggnnnnNNNNrR...',
      '.Nnnngnnnn.NNNNRR...',
      '..NNNwNNN..NNNRR....',
      '....xw.N...xNN......',
      '...xNN....xNNN......',
      '....................',
    ],
  },
  大魔導師: {
    size: 20,
    pal: { f: '#a89a98', F: '#6e6068', d: '#1a1418', e: '#ff3020', b: '#3a1a40', B: '#24102a', v: '#5a2a64', g: '#a8883a', G: '#6e5824', t: '#c8c0a8', T: '#8a8270', p: '#a050e0', P: '#e0b0ff', s: '#3a2a20' },
    rows: [
      '.....p..............',
      '....pPp.....tt......',
      '.....p.....tTTt.....',
      '..........tkTkt.....',
      '..vv....vv.tTTt.....',
      '..vbv..vbv..TT......',
      '..vbbbbbbv..s.......',
      '..vbBffffB..s...p...',
      '..vbfefeFB..s..pPp..',
      '..vbfffffB..s...p...',
      '..gvbFttFBg.s.......',
      '.gvvbbttbbBgs.......',
      '.vvbbbgtbbBfs.......',
      '.vbbbbgbbbBBs.......',
      '.vbbbbgbbbbBs.......',
      'vbbbbbgbbbbBBs......',
      'vbbbbbgbbbbbBs......',
      'BGBGBBgBBGBGBs......',
      '.p.......p..........',
      '....................',
    ],
  },
  魔王: {
    size: 32,
    mirror: true,
    pal: { s: '#5a2a3a', S: '#3a1a28', x: '#7a3a4e', h: '#b8ac94', H: '#7a705e', e: '#ff3020', E: '#ffd040', w: '#e8e0c8', a: '#3a3444', A: '#24202c', g: '#9a7a30', G: '#5e4a1e', c: '#4a1a22', C: '#2a0e14', p: '#8a4ab0', P: '#d0a0ff' },
    rows: [
      '................',
      '..h.............',
      '..hh............',
      '..Hh............',
      '...Hh...........',
      '...Hhh.....g...g',
      '....Hhh...gg..gg',
      '.....Hhhh.gggggg',
      '......HHhxssssss',
      '........sxssssss',
      '.......sxssEesss',
      '.......ssssSSsss',
      '.h......Sssskwkw',
      '.hH..h..SSsskkkk',
      '.aH.hH...SSSSSSS',
      '..aaaaaaa.gAAAAA',
      '.aaxxaaaaagAAaAA',
      '.axaaaaaAAgAaeaA',
      '.AaaaaaAAcgAAaaA',
      '..AAAAAAccgAAAAA',
      '..sSccccccgAaaAA',
      '..sScccccCgAaAAA',
      'P.sSccccCCgAAAAa',
      'pwsSwcccCCgaaAAA',
      '.w.w.ccCCCgAAAAA',
      '.p..ccCCCCgAAAAA',
      '....ccCCCCAAaAAA',
      '....cCCCCAAaAAAA',
      '...ccCCCCAAAAAAA',
      '...cCCCCAAAA.AAA',
      '..ccCCCCAAA.....',
      '................',
    ],
  },
  影の暗殺者: {
    pal: { d: '#1e1a26', D: '#121018', x: '#2e2838', e: '#ff3030', a: '#d0d8e4', A: '#8a93a3', r: '#4a1a2a', R: '#2e101a' },
    rows: [
      '................',
      '......xxx.......',
      '.....xddDD......',
      '....xeedDD......',
      '....dddDDD.rr...',
      '.....DdDDrrR.r..',
      '..a.ddddDDD..R..',
      '.aA.dddddDDD....',
      'aA.dddDdddDD....',
      '..dd.ddDddDD....',
      '.....dddDDDD.a..',
      '....dDD.dDDDaA..',
      '...dDD...dDaA...',
      '...dD.....dD....',
      '..DD.....DD.....',
      '................',
    ],
  },
  骨の竜騎兵: {
    pal: { h: '#c8c0a8', H: '#8a8270', e: '#e03030', r: '#6a5a40', R: '#3e3426', l: '#a8b0bc', L: '#5a6170', s: '#4a4038', S: '#2e2822', x: '#7a2a2a', w: '#e8e0c8' },
    rows: [
      '..........h.....',
      '.........hH.....',
      '....hhhhhhH.....',
      '..hhhheHhH......',
      '.hwhwhhhhH..x...',
      '......hHH..xx...',
      '....rrrRRrxx....',
      'llllsrrrRRllllll',
      '...sSsrRrRR.....',
      '...sxSrrRRRh....',
      '...sSsrRRRR.....',
      '...sSs.hH.H.....',
      '....s..hH.hH....',
      '.......RR..RR...',
      '......RRR..RRR..',
      '................',
    ],
  },
  血の祭壇: {
    pal: { s: '#5a5058', S: '#3a3238', l: '#7a7078', b: '#8a1a1a', B: '#5a0e10', r: '#c02020', e: '#f0d040', E: '#c89020', d: '#1a0a0a', c: '#d8d0b8', f: '#f0a030' },
    rows: [
      '................',
      '..f.........f...',
      '..c..b..b...c...',
      '..c.bbrbrbb.c...',
      '.lllllllllllllS.',
      '.sbsssbsssbsssS.',
      '..sbsrrrrssbsS..',
      '..sbrdeeedrsSS..',
      '..ssreEdEersSS..',
      '..sbrdeeedrsbS..',
      '..ssbrrrrrssbS..',
      '..sbs.ss.sbsSS..',
      '..ssssssssssSS..',
      '.lllllllllllSSS.',
      '.SSSSSSSSSSSSSS.',
      '..b..B....B..b..',
    ],
  },
  堕ちた聖職者: {
    pal: { g: '#c8a040', G: '#7a6028', w: '#c8c4b8', W: '#8a867c', d: '#1e1a22', D: '#2e2834', f: '#a89a90', F: '#6e625c', e: '#ff3030', t: '#3a1a2a', p: '#c050ff', r: '#7a1a22' },
    rows: [
      '....gg.gg.......',
      '...G......g.....',
      '....gg.ggG......',
      '.....ffff.......',
      '....fefeF.......',
      '....ffffF.......',
      '.....FrF........',
      '....wwrwwdd.....',
      '...wwDrwddDd....',
      '..tttwrdwdDd....',
      '..tptwrdwDDd....',
      '..tttfrwdwDD....',
      '....wWrdwdDD....',
      '....wWWddDDd....',
      '...wW.dD.wDDd...',
      '................',
    ],
  },
};
