// Party members: 16x16, front facing. Outline is added automatically (4-neighbour) unless outline:false.
const SKIN = { f: '#d0a888', F: '#9a7258', d: '#1a1418' };
const STEEL = { a: '#8a93a3', A: '#5a6170', S: '#3a3f4c' };

export const JOBS = {
  戦士: {
    pal: { ...SKIN, ...STEEL, h: '#3a2a22', L: '#6b4a32', M: '#4a3222', u: '#7a6a58', w: '#5a4030', b: '#2e2018', o: '#b08a3a', r: '#8a3a32' },
    rows: [
      '................',
      '.....hhhh..aaa..',
      '....hhhhhh.aAAa.',
      '....hffffh.aAAa.',
      '....fdffdf..aw..',
      '....frfffF...w..',
      '.....fFFF....w..',
      '..uuuLLLLuuu.w..',
      '.uuuLLLLLLuuuw..',
      '.ffLLMLLMLLLff..',
      '.ff.LLLLLL...w..',
      '....bbbobb...w..',
      '....MMMMMM...w..',
      '....MM..MM......',
      '....SS..SS......',
      '................',
    ],
  },
  騎士: {
    outline: false,
    pal: { a: '#8a93a3', A: '#5a6170', r: '#8c2a2e', R: '#5e1a1e', o: '#c9a54a', f: '#d9b08c', d: '#2a2030' },
    rows: [
      '......kkkk......',
      '....kkaaAAkk....',
      '...kaaaaaAAAk...',
      '...kaaakkkkAk...',
      '...kakffffkAk...',
      '...kakfdkdfkk...',
      '...kaaffffkAk...',
      '....kkAAAAkk....',
      '..kkrrrrrrrrkk..',
      '.karrrrooorrrak.',
      '.karrrooooorrak.',
      '.kakrrrooorrkak.',
      '..k.kRrrrrRk.k..',
      '....kRRkkRRk....',
      '....kAkk.kAk....',
      '....kkk..kkk....',
    ],
  },
  暗黒騎士: {
    pal: { n: '#3e3848', N: '#25212d', x: '#615872', e: '#e03030', p: '#4a2240', P: '#2e1428', a: '#8a93a3' },
    rows: [
      '................',
      '...x......x.....',
      '...xx....xx.....',
      '....xxnnxx......',
      '....xnnnnN......',
      '....NeNNeN......',
      '....nNNNNN......',
      '..pxxNNNNxxp....',
      '.ppxnNnnNnxpp...',
      '.ppnNNeNNNnpp.a.',
      '.ppNnNNNNnNppxa.',
      '.PPNnnnnnnNPP.a.',
      '.PP.NNNNNN.PP.a.',
      '.P..NN..NN..P.a.',
      '....xN..xN......',
      '................',
    ],
  },
  侍: {
    pal: { ...SKIN, ...STEEL, g: '#b0903a', r: '#7a2a2a', R: '#4e1a1c', S: '#26242e', s: '#4a3a4a' },
    rows: [
      '................',
      '...g......g.....',
      '....g....g...a..',
      '....SggggS...a..',
      '...SSSSSSSS..a..',
      '....SdffdS...a..',
      '....SffffS...a..',
      '..RRRSFFSRRR.a..',
      '.RRRrrrrrrRRRg..',
      '.frRRRRRRRRrff..',
      '.f.rrrrrrrr..S..',
      '...rRrRrRrR.....',
      '...ssssssss.....',
      '...sss..sss.....',
      '...SS....SS.....',
      '................',
    ],
  },
  白魔道士: {
    pal: { ...SKIN, w: '#cfcabd', W: '#8e8a80', V: '#5e5a54', g: '#b0903a', s: '#5a4030' },
    rows: [
      '................',
      '.ggg..wwww......',
      '.g.g.wwwwwW.....',
      '.ggg.wffffW.....',
      '..s.wfdffdW.....',
      '..s.wffffFW.....',
      '..s.wWffFWW.....',
      '..s.wwwgwwWW....',
      '..fwwwwgwwwWW...',
      '..swwwwgwwwWW...',
      '..s.wwwgwwWW....',
      '..s.wwwgwwWW....',
      '..s.wwwgwwWWW...',
      '..s.wwwgwwWWW...',
      '..s.VVVVVVVVV...',
      '................',
    ],
  },
  黒魔道士: {
    pal: { f: '#b8a898', F: '#7e7068', d: '#1a1418', b: '#2e2a44', B: '#1c1a2c', v: '#4a4466', g: '#8e8a86', e: '#8a5ae0', E: '#c8a8ff', s: '#4a3a30' },
    rows: [
      '......b.........',
      '......vb........',
      '.....vbbB....e..',
      '.....vbbbB..eEe.',
      '....vbbbbbB..e..',
      '....vBffffB..s..',
      '....bfdffdB..s..',
      '....bFggggB..s..',
      '...vbbggggbBBf..',
      '...vbbbggbbbBs..',
      '...vbbbbbbbbBs..',
      '...vbbbbbbbbBs..',
      '..vbbbbbbbbbBs..',
      '..vbbbbbbbbbBs..',
      '..BBBBBBBBBBBs..',
      '................',
    ],
  },
  赤魔道士: {
    pal: { ...SKIN, a: '#a8b0bc', r: '#8a2e30', R: '#5a1c20', h: '#3a2a22', g: '#b0903a', c: '#c8c0b0', S: '#2a2224', b: '#4a3a30' },
    rows: [
      '................',
      '......hhhh......',
      '.....hhhhhh.....',
      '.....hggggh.....',
      '.....hdffdh.....',
      '.....hffffF.....',
      '....rRfFFfRr....',
      '...rrrRccRrrr...',
      '..rrrrRcgRrrrr..',
      '.brrRrRccRrRrr..',
      '.bbrRrRccRrRrf..',
      '.bbrRrRccRrrRg..',
      '..RrrrRccRrrRa..',
      '..RRrRRRRRRrRa..',
      '....SS..SS...a..',
      '................',
    ],
  },
  呪術師: {
    pal: { m: '#c8bfa8', M: '#8e8672', e: '#d03030', o: '#4a4a30', O: '#2e2e1e', q: '#6a6440', h: '#2a2420', b: '#d8d0b8', F: '#7a5a48', r: '#7a2a2a' },
    rows: [
      '................',
      '....h.h..h......',
      '....hhhhhhh.....',
      '...hhmmmmmhh....',
      '...hmemmmeMh....',
      '...hmmmMmmMh....',
      '...hhMkrkMhh....',
      '..h.hMmmmMh.h...',
      '..qqoooooooqq...',
      '.qqoooOoooOooq..',
      '.boqoOooOoOqob..',
      '.b.oOooooOoo.b..',
      '..qoOoOoOooOq...',
      '..oOoOoOoOoOo...',
      '...O.O.FF.O.O...',
      '................',
    ],
  },
  盗賊: {
    pal: { ...SKIN, ...STEEL, c: '#3a4038', C: '#24281f', n: '#545a4c', L: '#4a3222', b: '#2a1e16', o: '#8a7a3a' },
    rows: [
      '................',
      '......cccc......',
      '.....ccccnc.....',
      '....cccccccn....',
      '....cCdffdCc....',
      '....cCCCCCCc....',
      '.....cCCCCc.....',
      '...ncccLLcccn...',
      '..nccLLLLLLccn..',
      '..fcCLLLLLLCcf..',
      '.a.cCbbobbbCc.a.',
      '.a.cCCCCCCCCc.a.',
      '....cCC..CCc....',
      '....CC....CC....',
      '....LL....LL....',
      '................',
    ],
  },
  狩人: {
    pal: { ...SKIN, g: '#4a5a38', G: '#2e3a24', l: '#6a7a50', w: '#6a4a2a', s: '#a8a090', q: '#7a5a3a', p: '#b8b0a0', L: '#4a3222' },
    rows: [
      '................',
      '..w...gggg......',
      '.w.s.gggggl.....',
      '.w.s.gGffffg....',
      'w..s.gfdffdg....',
      'w..s.gffffFg..p.',
      'w..s..gfFFg..qp.',
      'w..sgggllgggqq..',
      'wf.gglllllggqg..',
      'w.fgGlLLLlGGg...',
      'w..fGllllllGf...',
      'w..s.GllllGG....',
      '.w.s.GGllGGG....',
      '.w.s.GG..GG.....',
      '..w..LL..LL.....',
      '................',
    ],
  },
  錬金術師: {
    pal: { ...SKIN, h: '#5a4a3a', o: '#b08a3a', O: '#e0c070', t: '#3a5a5a', T: '#243c3c', L: '#7a5a3a', M: '#4e3824', v: '#7ab040', V: '#c8e080', g: '#a8b0b8' },
    rows: [
      '................',
      '.....hhhhhh.....',
      '....hhhhhhhh....',
      '....oOohhoOo....',
      '....hffffffh....',
      '....fdffffdf....',
      '.....ffFFff.....',
      '...ttTffffTtt...',
      '..ttLLLLLLLLtt..',
      '..tTLLMLLMLLTt..',
      '..ff.LLLLLL.fg..',
      '.....LLLLLL.gvg.',
      '.....LLMMLL.gVg.',
      '.....TT..TT..g..',
      '.....MM..MM.....',
      '................',
    ],
  },
  吟遊詩人: {
    pal: { ...SKIN, h: '#6a4a2a', c: '#3a5a58', C: '#243a3a', y: '#a08a4a', Y: '#6a5a30', p: '#8a3a3a', w: '#7a5030', W: '#4a3020', s: '#c8c0a0', L: '#3a2a20' },
    rows: [
      '..........p.....',
      '.....cccccp.....',
      '....cccccccp....',
      '...ccCCCCCCC....',
      '....hffffffh....',
      '....hfdffdfh....',
      '.....fffFff.....',
      '...yyycFcyyy....',
      '..yyYccccYyyy...',
      '..yYcwwwwcYyy...',
      '..fYwWWWWwWff...',
      '...cwWsWWwcc....',
      '...cCwwwwCcc....',
      '....CC..CCs.....',
      '....LL..LL......',
      '................',
    ],
  },
  踊り子: {
    pal: { ...SKIN, h: '#4a2a2a', H: '#2e1a1c', r: '#8a3a4a', R: '#5a2232', g: '#b0903a', v: '#a87a8a', V: '#6e4a5a' },
    rows: [
      '.......g........',
      '.....hhhhh......',
      '....hhhhhhh.....',
      '....hffffhh.....',
      '...hhdffdfhh....',
      '...hhffffFhH....',
      '..hhH.fFFHhH....',
      '..hH.ffffffHH...',
      '.vf.grrrrrgf.v..',
      '.v.f.ffffFf..v..',
      '.v...ffFFf...v..',
      '..v.ggrrrgg.v...',
      '...vvrRrRrvv....',
      '....VrRrRrV.....',
      '.....ff.ff......',
      '................',
    ],
  },
  召喚士: {
    pal: { ...SKIN, h: '#c8bca0', H: '#8a806a', p: '#3a2e4a', P: '#241c30', q: '#5a4a6e', g: '#40b0a0', G: '#a0f0e0', o: '#b0903a' },
    rows: [
      '.h..........h...',
      '.hh........hh...',
      '..Hh.pppp.hH....',
      '...Hpppppph.....',
      '....pPffffp.....',
      '....pfdffdp.....',
      '....pffffFp.....',
      '...qqpfFFpqq....',
      '..qqppopoppqq...',
      '.qqpppooopppq...',
      '.fgpppoPopppfg..',
      '.gGg.ppoppp.gGg.',
      '..g..ppoPpP..g..',
      '....pppPppPP....',
      '....PPPPPPPP....',
      '................',
    ],
  },
};

export const UNKNOWN = {
  pal: { s: '#3a3644', S: '#26232e', q: '#8a8496' },
  rows: [
    '................',
    '......ssss......',
    '.....ssssSS.....',
    '.....sqqqsS.....',
    '.....sssqsS.....',
    '......sqsS......',
    '......SsSS......',
    '....ssssqsSS....',
    '...ssssssssSS...',
    '...ssssqsssSS...',
    '...sS.ssssS.S...',
    '......ssSSS.....',
    '......sS.SS.....',
    '......sS.SS.....',
    '......SS.SS.....',
    '................',
  ],
};
