// 12x12 icons. Outline auto-added.
const STEEL = { a: '#a8b0bc', A: '#6a7280', S: '#454b58' };
const GOLD = { o: '#c9a54a', O: '#8a6e2a', y: '#e8d080' };
export const ICONS = {
  battle: { pal: { ...STEEL, w: '#6a4a2a', o: '#c9a54a' }, rows: [
    '............',
    '.a........a.',
    '..a......a..',
    '..Aa....aA..',
    '...Aa..aA...',
    '....AaaA....',
    '.....Aa.....',
    '....aAAa....',
    '..owaA.Awo..',
    '..ow.....wo.',
    '.ww......ww.',
    '............',
  ] },
  elite: { pal: { b: '#d8d0b8', B: '#8e8672', h: '#8a3a32', H: '#5a2020', e: '#e03030' }, rows: [
    '............',
    '.h........h.',
    '.hH......Hh.',
    '..hHbbbbHh..',
    '...bbbbbbB..',
    '..bbbbbbbbB.',
    '..beebbeebB.',
    '..bkkbbkkbB.',
    '...bbBBbbB..',
    '...bkbkbkB..',
    '....BBBBB...',
    '............',
  ] },
  rest: { pal: { y: '#f0d060', o: '#e07a20', r: '#a8341a', w: '#6a4a2a', W: '#3e2a18' }, rows: [
    '............',
    '.....y......',
    '....yo......',
    '....yoy.....',
    '...yoorr....',
    '...yorrro...',
    '...oryyro...',
    '....ryyr....',
    '..wWWooWWw..',
    '.wwWWwwWWww.',
    '..WW....WW..',
    '............',
  ] },
  shop: { pal: { b: '#7a5a3a', B: '#4e3824', l: '#9a7a52', o: '#c9a54a', y: '#e8d080', s: '#b8a888' }, rows: [
    '............',
    '....bsbb....',
    '.....BB.....',
    '....lbbB....',
    '...lbbbbB...',
    '..lbbbbbbB..',
    '..bbbbbbbB..',
    '..bbbbbbBB.y',
    '..bbbbbBBBoy',
    '...BBBBBBoo.',
    '.......oo...',
    '............',
  ] },
  treasure: { pal: { w: '#7a5030', W: '#4e3220', l: '#9a6a40', o: '#c9a54a', O: '#8a6e2a' }, rows: [
    '............',
    '............',
    '..llllllll..',
    '.lwwwwwwwwW.',
    '.owwwwwwwWo.',
    '.ooooOOoooO.',
    '.wwwwoowwwW.',
    '.wwwwOOwwwW.',
    '.owwwwwwwWo.',
    '.WWWWWWWWWW.',
    '............',
    '............',
  ] },
  event: { pal: { p: '#c8bca0', P: '#8a806a', q: '#5a2a2a' }, rows: [
    '............',
    '.pppppppppP.',
    '..pppqqppP..',
    '..ppqppqpP..',
    '..pppppqpP..',
    '..ppppqppP..',
    '..pppqpppP..',
    '..pppppppP..',
    '..pppqpppP..',
    '.pppppppppP.',
    '..PPPPPPPP..',
    '............',
  ] },
  boss: { pal: { n: '#4a4458', N: '#2a2634', x: '#6e6880', e: '#e03030', o: '#8a6e2a' }, rows: [
    '............',
    '............',
    '.x...x...x..',
    '.xn.xnn.xn..',
    '.xnnxnnnxnN.',
    '.xnnnnnnnnN.',
    '.xneNNeNNeN.',
    '.xnnnnnnnnN.',
    '.NNNNNNNNNN.',
    '.oNoNoNoNoN.',
    '............',
    '............',
  ] },
  item: { pal: { g: '#a8b8b8', c: '#8a2a3a', C: '#5a1a26', l: '#c84a5a', w: '#6a4a2a' }, rows: [
    '............',
    '.....ww.....',
    '.....gg.....',
    '.....gg.....',
    '....gccg....',
    '...glccCg...',
    '..gcllcccg..',
    '..gccccCCg..',
    '..gcccCCCg..',
    '...gCCCCg...',
    '....gggg....',
    '............',
  ] },
  book: { pal: { b: '#4a2a3a', B: '#2e1824', o: '#c9a54a', p: '#d8d0b8', P: '#a89e84' }, rows: [
    '............',
    '..bbbbbbbb..',
    '.obbbbbbbbp.',
    '.obbbobbbbp.',
    '.obbobobbbp.',
    '.obobbbobbp.',
    '.obbobobbbp.',
    '.obbbobbbbp.',
    '.oBBBBBBBBp.',
    '.oPPPPPPPPP.',
    '..ooooooooo.',
    '............',
  ] },
  weapon: { pal: { ...STEEL, w: '#6a4a2a', o: '#c9a54a' }, rows: [
    '............',
    '.........aa.',
    '........aaA.',
    '.......aaA..',
    '......aaA...',
    '.....aaA....',
    '..o.aaA.....',
    '...oaA......',
    '...wo.......',
    '..w..o......',
    '.o..........',
    '............',
  ] },
  armor: { pal: { ...STEEL, r: '#8c2a2e' }, rows: [
    '............',
    '.aaA....aAA.',
    '.aaaaAAaaAA.',
    '.aaaaaaaaAA.',
    '..aaaaaaAA..',
    '..aaAaaAAA..',
    '..aaaAAAAA..',
    '..rrrrrrrr..',
    '..aaAAAAAA..',
    '...AAAAAA...',
    '............',
    '............',
  ] },
  acc: { pal: { ...GOLD, r: '#c03040', R: '#e87080' }, rows: [
    '............',
    '.....rR.....',
    '....rrrR....',
    '....orro....',
    '...oo..oo...',
    '..oy....oO..',
    '..o.....OO..',
    '..oo....OO..',
    '...oO..OO...',
    '....OOOO....',
    '............',
    '............',
  ] },
  gold: { pal: GOLD, rows: [
    '............',
    '....oooo....',
    '...oyyyoO...',
    '..oyyoOyoO..',
    '..oyoyyOoO..',
    '..oyoyyOoO..',
    '..oyyOOoOO..',
    '...oOOOOO...',
    '....OOOO....',
    '............',
    '............',
    '............',
  ] },
  pair: { pal: { a: '#a8b0bc', A: '#6a7280', o: '#c9a54a', O: '#8a6e2a' }, rows: [
    '............',
    '............',
    '..aaa..ooo..',
    '.a...ao...O.',
    'a...oaO....O',
    'a...o.a....O',
    'a...O.a...O.',
    'A...OAo...O.',
    '.A...AO..O..',
    '..AAA..OOO..',
    '............',
    '............',
  ] },
  job: { pal: { o: '#c9a54a', O: '#8a6e2a', y: '#e8d080', r: '#8c2a2e' }, rows: [
    '............',
    '.....yo.....',
    '.....oO.....',
    '....yoOO....',
    '.yoooorOOOO.',
    '..ooorrrOO..',
    '...ooorOO...',
    '...ooOOOO...',
    '..ooO..OOO..',
    '..oO....OO..',
    '............',
    '............',
  ] },
  floor: { pal: { p: '#c8bca0', P: '#8a806a', r: '#8c2a2e', g: '#6a7a50' }, rows: [
    '............',
    '.pppP.pppP..',
    '.ppgPPppppP.',
    '.pgPPrppgPP.',
    '.ppPPprpgPP.',
    '.ppPPpprPPP.',
    '.pgPPppPPrP.',
    '.ppPPpppPPr.',
    '.ppPPrgpPPP.',
    '.pPP.ppPPP..',
    '............',
    '............',
  ] },
  blessing: { pal: { y: '#f0e0a0', o: '#c9a54a', O: '#8a6e2a' }, rows: [
    '............',
    '.....y......',
    '..o..y..o...',
    '...o.o.o....',
    '....ooo.....',
    '.yyoo.ooyy..',
    '....ooo.....',
    '...o.o.o....',
    '..o..y..o...',
    '.....y......',
    '............',
    '............',
  ] },
  skull: { pal: { b: '#d8d0b8', B: '#8e8672' }, rows: [
    '............',
    '...bbbbbB...',
    '..bbbbbbbB..',
    '..bbbbbbbB..',
    '..bkkbkkbB..',
    '..bkkbkkbB..',
    '..bbbkbbBB..',
    '...bbbbbB...',
    '...bkbkbB...',
    '....BBBB....',
    '............',
    '............',
  ] },
  heart: { pal: { r: '#b02a34', R: '#6e161e', l: '#e06a70' }, rows: [
    '............',
    '............',
    '..rr...rr...',
    '.rllr.rrrR..',
    '.rlrrrrrrR..',
    '.rrrrrrrrR..',
    '..rrrrrrR...',
    '...rrrrR....',
    '....rRR.....',
    '.....R......',
    '............',
    '............',
  ] },
};
